### ISSUE TITLE
Add documentation for passing messages to WithCriteria

### ISSUE THREAD

**Issue by pascalberger** [cake-build/website#1037]
### What You Are Seeing?
cake-build/cake#1594 added the possibility to pass a message with `WithCriteria`. This possibility is not mentioned currently in [documentation](https://cakebuild.net/docs/fundamentals/criteria).

### What is Expected?
Possibility to pass message to `WithCriteria` should be added to [documentation](https://cakebuild.net/docs/fundamentals/criteria).
Including details like, that the message will be printed with `Verbose` verbosity.

**Comment by nikhilagrawaldotnet** [comment]
@augustoproiete @pascalberger - Guys, could you pls review and approve this PR?
