### ISSUE TITLE
Add information about Visual Studio Task Runner

### ISSUE THREAD

**Issue by gep13** [cake-build/website#106]
https://gitter.im/cake-build/cake?at=57608a03da1c26b045361237

**Comment by agc93** [comment]
Oh hey, that's me! :+1: 

I'm happy to have a look at this, but it's obviously not going to fit in with the format of the other "Editors" pages, since it's not to do with Intellisense or highlighting. Are there any other templates or anything I should use? 

Or if you guys are looking after this, I'll let more experienced hands work..

**Comment by gep13** [comment]
@agc93 I was going to take this when I got a second, but happy for you to take it if you want.  We don't have any templates as such, so don't have anything that I can point you at, sorry.  I was thinking just a simple page with the steps on how to set up the task, and also some screenshots to help along the way, and a final screenshot showing the expected operation of the task.

**Comment by enkafan** [comment]
Slightly related, I was working on calling my build script from VS Code. Maybe this new section could also house this information too. For what it's worth, here's the config I settled on.

```json
{
    "version": "0.1.0",
    "isShellCommand": true,
    "showOutput": "always",
    "windows" :{
	    "command": "${env.windir}\\sysnative\\windowspowershell\\v1.0\\PowerShell.exe",
            "args": [   
                "-ExecutionPolicy",
                "Unrestricted",
                "-NoProfile",
                "-file",
                "build.ps1",
                "-target"
            ]
    },    
    "tasks": [
        {
            "taskName": "build",
            "suppressTaskName": true,
            "isBuildCommand": true,
            "args": [
                "build"
            ]
        },
        {
            "taskName": "Test",
            "suppressTaskName": true,
            "isTestCommand": true,
            "args": [
                "run-unit-tests"
            ]
        }
    ]
}```

Assumes you have two tasks named `build` and `run-unit-tests` in your cake file. This is just for a Windows setup, but I've tried to keep the tasks themselves workable for someone running *nix too.

**Comment by gep13** [comment]
@agc93 fairly sure this is done, so closing it off.
