### ISSUE TITLE
Add #addin widget to addin pages

### ISSUE THREAD

**Issue by mgnslndh** [cake-build/website#1095]
Just like for packages at NuGet.org it would be nice to have a widget on the addin page that displays the #addin directive for the addin and lets you copy it to the clipboard.

![image](https://user-images.githubusercontent.com/1139118/95547880-37f6cc00-0a04-11eb-9a2d-71235650d3b8.png)

![image](https://user-images.githubusercontent.com/1139118/95547900-45ac5180-0a04-11eb-8580-d4aba4c986c9.png)

```
#addin nuget:?package=Cake.UServer&version=0.1.3
```

**Comment by gep13** [comment]
@mgnslndh I think this is a great idea! Are you planning on taking a stab at this?

**Comment by pascalberger** [comment]
That's a great idea 👍  There are also other related issues in this area. I created https://github.com/cake-build/website/issues/1096 to start with a quick UI mockup for the whole addin section, to avoid doing work which need to redone soon after, once we go to the next issue.

**Comment by devlead** [comment]
What would be cool would be to like paket he listed in the official gallery... 

https://github.com/NuGet/NuGetGallery/pull/4638/files

**Comment by devlead** [comment]
> @devlead that would be cool. But I guess not all packages are appropriate for Cake and how would determine which directive to use? #addin/#tool 

Well, `#addin`directive can reference any .NET assembly, so not limited to addins, just does more magic if it is.

**Comment by pascalberger** [comment]
Mockup for a new extension page which shows usage instructions for addins: https://github.com/cake-build/website/issues/1096#issuecomment-711096108
