### ISSUE TITLE
Improve ordering of search results

### ISSUE THREAD

**Issue by pascalberger** [cake-build/website#1110]
We currently have the following parts of the page in our search index:

- blog
- docs
- dsl
- addins
- faq

All have the same priority. We should weight them to improve search results.

**Comment by pascalberger** [comment]
My suggestion:

- blog -2 (should be fallback for stuff not found anywhere else)
- docs +5 (should be the most up to date content)
- dsl +2 (helpful to search for funcitonality, especially once https://github.com/cake-build/website/issues/1111 is done)
- addins -5 (most results I would expect to be returned already by the DSL section, which are more helpful)
- faq 0 (would like to integrate this into docs later)

@cake-build/cake-team Opinions?

**Comment by gep13** [comment]
@pascalberger this makes sense to me :+1:
