### ISSUE TITLE
Show aliases without extension parameter

### ISSUE THREAD

**Issue by pascalberger** [cake-build/website#1153]
When listing aliases we currently show the syntax of the extension method. 

![image](https://user-images.githubusercontent.com/2190718/97095076-47f4e980-165b-11eb-8653-3c6b07ae5393.png)

That they are extensions is an implementation detail from a user point of view, and we therefore should show the syntax as the user will call it (without the `ICakeContext` parameter)

**Comment by devlead** [comment]
Not sure about this, that would also lose how they're invoked on cake/setup/task context and in frosting.

**Comment by devlead** [comment]
Maybe we should document both some way 🤔

**Comment by pascalberger** [comment]
> Not sure about this, that would also lose how they're invoked on cake/setup/task context and in frosting.

But also in these cases you should call them as extensions and not as static methods.

> Maybe we should document both some way 🤔

We can do something like this, but IMHO this leads to even more confusion. 

![image](https://user-images.githubusercontent.com/2190718/97107693-2f231d00-16c9-11eb-9f25-2f63e62f39b5.png)

From a user perspective aliases should always be called as an extension. So my suggestion would be to get rid of the `ICakeContext` parameter in the link and add documentation in which cases the user need to call `Context.Foo()` and in which cases `Foo()` is enough (because this is another magic thing which currently is not documented somewhere).

**Comment by devlead** [comment]
Ok makes sens, as long as it remains on details.

**Comment by pascalberger** [comment]
> Ok makes sens, as long as it remains on details.

Yep, agree that we should keep API documentation as it is now

**Comment by pascalberger** [comment]
I updated documentation about aliases, including examples how to call them from script tasks and from Frosting: https://cakebuild.net/docs/fundamentals/aliases#calling-aliases
