### ISSUE TITLE
Aliases not shown for Cake.XmlDocMarkdown addin

### ISSUE THREAD

**Issue by pascalberger** [cake-build/website#1156]
For the Cake.XmlDocMarkdown addin no alias are shown on the [extension detail page](https://cakebuild.net/extensions/cake-xmldocmarkdown/):

![image](https://user-images.githubusercontent.com/2190718/97095297-e124ff80-165d-11eb-97c0-3c52f35ef4af.png)

**Comment by pascalberger** [comment]
Issue seems to be that the addins doesn't contain a `CakeAliasCategory` attribute

**Comment by augustoproiete** [comment]
> Issue seems to be that the addins doesn't contain a `CakeAliasCategory` attribute

I confirmed it was the case and adding the `CakeAliasCategory` attribute resolves it.

I opened PR https://github.com/ejball/XmlDocMarkdown/pull/111 in the addin repo to fix that.

**Comment by pascalberger** [comment]
> I confirmed it was the case and adding the `CakeAliasCategory` attribute resolves it.

There's are also other addins which miss the `CakeAliasCategory` and we also added this to the Addin Discoverer (see https://github.com/cake-contrib/Home/blob/master/Audit.xlsx). I already created PRs for some of the other addins.

While adding an addin category is defintely best practice, I keep this issue open, since on the extension page we should be able to list addins even without addin category (but we need addin category for references page).

**Comment by augustoproiete** [comment]
PR was merged (https://github.com/ejball/XmlDocMarkdown/pull/111) hopefully a new release will be up on nuget.org soon.

**Comment by augustoproiete** [comment]
Cake.XmlDocMarkdown v2.3.2 was released to NuGet and fixes the particular issue with this addin, and the docs now show correctly on the website:

[![image](https://user-images.githubusercontent.com/177608/105497488-473d1500-5c95-11eb-9b21-54c2572368bb.png)](https://cakebuild.net/extensions/cake-xmldocmarkdown/)

@pascalberger I opened https://github.com/cake-build/website/issues/1496 to track the more general issue you mentioned above, and closing this one as resolved
