### ISSUE TITLE
Add project url to extension metadata

### ISSUE THREAD

**Issue by pascalberger** [cake-build/website#1195]
Some extensions have a dedicated site for documentation. We should provide an attribute where this can be set. Addin discoverer should sync this with the project site of the NuGet package

**Comment by pascalberger** [comment]
Current logic in Addin Discoverer also maps project URL to repo URL if no repo URL is defined, which then looks weird on website (e.g. https://cakebuild.net/extensions/cake-xamarin-binding-util/).

**Comment by augustoproiete** [comment]
> We should provide an attribute where this can be set

Are you thinking of another attribute in the YAML (manually maintained) or something exposed to add-in authors (e.g. attribute in `Cake.Core.Annotations`)?

BTW, in this particular case the project URL points to a URL that redirects to the GitHub repo https://go.microsoft.com/fwlink/?linkid=864959 (probably for tracking) so I suspect they would use the same URL for repository URL as well.

Maybe it makes sense for the AddinDiscoverer to unpack the URL?

**Comment by pascalberger** [comment]
> Are you thinking of another attribute in the YAML (manually maintained) or something exposed to add-in authors (e.g. attribute in `Cake.Core.Annotations`)?

Yes, another attribute in the YAML (RepositoryUrl and ProjectUrl), identical to what nuget.org does nowadays:

![image](https://user-images.githubusercontent.com/2190718/102051399-cf054900-3de4-11eb-818f-07a2236980cb.png)

Addin Discoverer can set both based on Addin metadata. The logic to use project URL as repository URL in Addin Discoverer comes from a time where NuGet packages didn't have repo metadata and most addins (but not all as your example shows) have used project URL pointing to the GitHub repo.

**Comment by Jericho** [comment]
This is being worked on [here](https://github.com/cake-contrib/Cake.AddinDiscoverer/issues/153). AddinDiscoverer will include both the repo URL and the project URL in the generate YAML.
