### ISSUE TITLE
Add PropertyType to properties table in api pages

### ISSUE THREAD

**Issue by ristaloff** [cake-build/website#123]
The properties table in the api pages would be more readable/informative if it also had a column with the property type in it.
Take this page as an example:
http://cakebuild.net/api/cake.common.tools.gitversion/cc080ec6

It could look something like this:
![image](https://cloud.githubusercontent.com/assets/4353303/17022053/208a1ab2-4f4c-11e6-802b-d61503a9cfd5.png)

**Comment by ristaloff** [comment]
#124

**Comment by gep13** [comment]
@ristaloff this will be available after the next deployment of the website.
