### ISSUE TITLE
Document usage of Settings_ShowProcessCommandLine

### ISSUE THREAD

**Issue by gep13** [cake-build/website#1234]
I thought we had an issue for this, but I looked and I couldn't see one.

**Comment by pascalberger** [comment]
Closing as a duplicate of #907

**Comment by gep13** [comment]
That is bizarre!  I searched, but I couldn't find that issue!  Apologies!

**Comment by pascalberger** [comment]
> That is bizarre! I searched, but I couldn't find that issue! Apologies!

It didn't include `Settings_ShowProcessCommandLine` anywhere :) Updated title now.

**Comment by gep13** [comment]
Ah, now the world makes sense again (well, a little bit more sense anyway!)
