### ISSUE TITLE
Prefer stable versions of packages over pre-release versions

### ISSUE THREAD

**Issue by augustoproiete** [cake-build/website#1262]
Once #1107 is resolved, we'll still be showing the most recent version of each package on the website, **whether it's a pre-release or not**.

An example the most recent version of [Cake.NSwag.Console](https://cakebuild.net/extensions/cake-nswag-console/) is [0.2.0-unstable0000](https://www.nuget.org/packages/Cake.NSwag.Console/0.2.0-unstable0000) and that's what the website shows, instead of showing the latest stable version [0.1.1](https://www.nuget.org/packages/Cake.NSwag.Console/0.1.1).

I suggest showing the latest stable version available instead over pre-release versions.

**Comment by pascalberger** [comment]
Related issue: https://github.com/cake-build/website/issues/184

IMHO logic should be like this:

- If a non pre-release version of an addin exists on nuget.org take the latest non pre-release version
- If only pre-release versions of an addin exist take the latest pre-release version, mark the addin as pre-release on the website and also update the install directives.

**Comment by augustoproiete** [comment]
> * If a non pre-release version of an addin exists on nuget.org take the latest non pre-release version
> * If only pre-release versions of an addin exist take the latest pre-release version

Agreed. I was thinking the same but the "ignore" in my title is misleading (copy/paste from issue #1107 I guess). Will fix.

> mark the addin as pre-release on the website and also update the install directives

Makes sense to me and seems like it would resolve #184.

Feel free to assign both #184 and #1262 (this issue) to me.

**Comment by pascalberger** [comment]
@augustoproiete I assigned you to this issue. Can't assign you to #184 since you haven't participated in that one yet, but feel free to just take it.
