### ISSUE TITLE
Remove Cake.Issues.Testing.yml (?)

### ISSUE THREAD

**Issue by augustoproiete** [cake-build/website#1289]
I noticed `Cake.Issues.Testing.yml` is present in the extensions folder but it's being listed as an extension in the website.

It seems it's being filtered out because it's defined in the YAML with [`Type: API`](https://github.com/cake-build/website/blob/716fc585c0308727a1411ad0dd74e1025700582c/extensions/Cake.Issues.Testing.yml#L1) instead of `Type: Addin`.

It also has not being kept up-to-date by the AddinDiscoverer (e.g. doesn't have the `TargetCakeVersion` attribute), but after some searching I found [this issue](https://github.com/cake-contrib/Cake.AddinDiscoverer/issues/23) and [comment from @pascalberger](https://github.com/cake-contrib/Cake.AddinDiscoverer/issues/23#issuecomment-706734416), and I understand this is expected.

Is there a plan to maintain this file manually (and eventually expose this API-type on a future section of the website) or should we remove it for now?

If the file is not going to be deleted, we might want to add some filters (by type) in the build pipeline to skip processing it.

**Comment by pascalberger** [comment]
This is a feature. Cake.Issues.Testing is not an addin, but something which we want to have listed in the [API documentation](https://cakebuild.net/api/Cake.Issues.Testing/). Addin discoverer handles only addins, so everything as exptected.

[Extension page](https://cakebuild.net/api/Cake.Issues.Testing/) only lists addins (and is planned to also list modules and recipes in the future).
