### ISSUE TITLE
Define version to use for every extension in YML file

### ISSUE THREAD

**Issue by pascalberger** [cake-build/website#1294]
Since we started to have version dependent data (`TargetCakeVersion`) in the extension YML file, it makes sense to also have the version from which this data comes added. This version should be used on the website for the specific extension.  

Corresponding issue for addin discoverer: https://github.com/cake-contrib/Cake.AddinDiscoverer/issues/143

**Comment by pascalberger** [comment]
Addin discoverer now maintains analyzed version of addin in the YAML file. We should update Website code to use this version of the addin and remove code for determine addin version from website build.

**Comment by augustoproiete** [comment]
@pascalberger I've updated the website to use the new `AnalyzedPackageVersion` instead of the version in #1356.

There's a couple more things it might be worth doing:
- Update AddinDiscoverer to add an `IsPrerelease` element to the YAML (`true` / `false`) to more easily replace [the logic that determines that](https://github.com/cake-build/website/blob/8f76caf0452fed5470b2e637b3d2e7bed8ac1988/nuget.cake#L47-L54) in the website (the other option is to use NuGet.Versioning in the views to parse the version string)
- Update the website build to use `AnalyzedPackageVersion` when [downloading the NuGet packages](https://github.com/cake-build/website/blob/8f76caf0452fed5470b2e637b3d2e7bed8ac1988/nuget.cake#L34-L64) rather than downloading latest

**Comment by pascalberger** [comment]
> @pascalberger I've updated the website to use the new `AnalyzedPackageVersion` instead of the version in #1356.

@augustoproiete Great, thanks for doing this 👍 

> * Update AddinDiscoverer to add an `IsPrerelease` element to the YAML (`true` / `false`) to more easily replace [the logic that determines that](https://github.com/cake-build/website/blob/8f76caf0452fed5470b2e637b3d2e7bed8ac1988/nuget.cake#L47-L54) in the website (the other option is to use NuGet.Versioning in the views to parse the version string)

This is what we had in the past. Logic to determine which version to use is already part of Addin Discoverer (the same logic that we use currently on the website). 

> * Update the website build to use `AnalyzedPackageVersion` when [downloading the NuGet packages](https://github.com/cake-build/website/blob/8f76caf0452fed5470b2e637b3d2e7bed8ac1988/nuget.cake#L34-L64) rather than downloading latest

Yes, that's the overall idea behind the flag. Addin Discoverer should determine which version to show on website and then website should use the version which is written in the YAML file.

**Comment by augustoproiete** [comment]
> This is what we had in the past. Logic to determine which version to use is already part of Addin Discoverer (the same logic that we use currently on the website)

Hmm, I'm not sure I understand what you mean. The website needs to know if the version stored in `AnalyzedPackageVersion` is prerelease or not, in order to [display the alert and modified preprocessor directive](https://github.com/cake-build/website/pull/1266). We can adapt the website build to parse `AnalyzedPackageVersion` and determine if it's prerelease (and continue to write the `.prerelease` file that flows to the view), or the AddinDiscoverer could add a new element `IsPrerelease` that has the metadata ready to use (would simplify the website build).

> Yes, that's the overall idea behind the flag. Addin Discoverer should determine which version to show on website and then website should use the version which is written in the YAML file.

I can bundle this with #1356 or create a separate PR. Let me know.

**Comment by pascalberger** [comment]
> > This is what we had in the past. Logic to determine which version to use is already part of Addin Discoverer (the same logic that we use currently on the website)
> 
> Hmm, I'm not sure I understand what you mean. The website needs to know if the version stored in `AnalyzedPackageVersion` is prerelease or not, in order to [display the alert and modified preprocessor directive](https://github.com/cake-build/website/pull/1266). We can adapt the website build to parse `AnalyzedPackageVersion` and determine if it's prerelease (and continue to write the `.prerelease` file that flows to the view), or the AddinDiscoverer could add a new element `IsPrerelease` that has the metadata ready to use (would simplify the website build).

Couldn't we just parse the version where we need to know if pre-release (and parsing should be as simple as checking if version contains a `-`), without the requirement to write to a file?

> 
> > Yes, that's the overall idea behind the flag. Addin Discoverer should determine which version to show on website and then website should use the version which is written in the YAML file.
> 
> I can bundle this with #1356 or create a separate PR. Let me know.

We can do this in a separate PR, then I can go ahead and already merge #1356

**Comment by augustoproiete** [comment]
> Couldn't we just parse the version where we need to know if pre-release (and parsing should be as simple as checking if version contains a -), without the requirement to write to a file?

We certainly could, it's just seems a little cleaner to have all the metadata about an addin coming from a single place.

**Comment by pascalberger** [comment]
> > Couldn't we just parse the version where we need to know if pre-release (and parsing should be as simple as checking if version contains a -), without the requirement to write to a file?
> 
> We certainly could, it just seems a little cleaner to have all the metadata about an addin coming from a single place.

@Jericho What's your opinion about adding an `IsPrerelease`  flag to the metadata?

**Comment by Jericho** [comment]
> @Jericho What's your opinion about adding an `IsPrerelease`  flag to the metadata?

Super easy for me to do. Also, it makes sense for the discoverer to give you as much data as possible an avoid the web site generator to dublicate any logic. 

The pre-release flag we used to track in yaml was true if package is pre-release OR any dependency is pre-release. Is that what we want or do we simply want to track if the package is pre-release?

I probably won't get to it today bu certainly early this week.

**Comment by pascalberger** [comment]
> The pre-release flag we used to track in yaml was true if package is pre-release OR any dependency is pre-release. Is that what we want or do we simply want to track if the package is pre-release?

Only if package is pre-release. Use-case is to show a banner and instructions how to use pre-release addins, like e.g. here: https://cakebuild.net/extensions/cake-vault/

**Comment by pascalberger** [comment]
I created https://github.com/cake-build/website/pull/1369 which will add an `AnalyzedPackageIsPrerelease` attribute to the extension YAML file.

**Comment by pascalberger** [comment]
@augustoproiete Should I assign this to you?

**Comment by augustoproiete** [comment]
@pascalberger I'm happy to take this one and branch off of your PR #1369

**Comment by pascalberger** [comment]
`AnalyzedPackageIsPrerelease` is now set in the YAML files
