### ISSUE TITLE
Add Modules section

### ISSUE THREAD

**Issue by gep13** [cake-build/website#131]
With the ability to support additional Cake Modules, I think we need an additional section on the site, which allows people to submit information about custom Cake modules, similar to what they can do for Addins.

**Comment by daveaglick** [comment]
Educate me - what's a module and how is it different from an addin? Is there a prototypical example module I should take a look at?

**Comment by devlead** [comment]
A module differs from an addin that it instead of adding features, replaces(or extends) core functionality in Cake
An example of this is [Cake.LongPath.Module](https://github.com/cake-contrib/Cake.LongPath.Module) which replaces the filesystem abstraction with one that supports long paths on .NET 4.5.

**Comment by gep13** [comment]
@daveaglick another example would be this:

https://github.com/larzw/Cake.Paket

Where the #tool and #addin pre-processor directives are being extended to include support for another package manager, in addition to nuget.

**Comment by gep13** [comment]
@daveaglick I think this one would be a good candidate for a pairing session as well.

**Comment by fwinkelbauer** [comment]
This documentation should also include how to handle the packages.config file in the tools/modules folder. Here's the `.gitignore` entry that I am using:

```
tools/**/*
!tools/packages.config
!tools/modules
!tools/modules/packages.config
```

Line 3 and 4 might look weird, but you seem to need both.

**Comment by gep13** [comment]
@fwinkelbauer yes, that is a good idea!

**Comment by pascalberger** [comment]
Mockup for replacing current addins page with an extension page which can also show modules: https://github.com/cake-build/website/issues/1096#issuecomment-711096108

**Comment by pascalberger** [comment]
https://github.com/cake-build/website/pull/1522 added support for showing modules in extension list.

Last missing part is adding yml files for known modules which is tracked by https://github.com/cake-contrib/Cake.AddinDiscoverer/issues/26.

**Comment by pascalberger** [comment]
Modules are now listed at https://cakebuild.net/extensions/. It's possible to filter the list to modules or addins through the filter UI or by searchging for `modules` or `addins`
