### ISSUE TITLE
Add documentation for Addin requests 

### ISSUE THREAD

**Issue by pascalberger** [cake-build/website#1355]
We have a repo where people can create issues for addin requests in the cake-contrib org: https://github.com/cake-contrib/addin-requests we should make this a first-class citizen by mentioning on website.

**Comment by pascalberger** [comment]
@cake-build/cake-team My suggestion would be to deprecate the addin-requests repo in favor of a custom category in GitHub discussions. Opinions?

**Comment by gep13** [comment]
I think that this is a good idea! Perhaps move any existing ones over into discussions?

**Comment by pascalberger** [comment]
> I think that this is a good idea! Perhaps move any existing ones over into discussions?

Yes that should be possible (by moving issues to Cake repo first, and then migrate them to discussion topics)

**Comment by pascalberger** [comment]
Discussion category created here: https://github.com/cake-build/cake/discussions?discussions_q=category%3A%22Extension+requests%22

Transfering issues won't work, since it's a different organization. I'll recreate them manually

**Comment by pascalberger** [comment]
Existing requests have been moved to GitHub discussions and https://github.com/cake-contrib/addin-requests repo has been archived
