### ISSUE TITLE
GitHub discussions instead of Gitter channel for Cake-Contrib

### ISSUE THREAD

**Issue by Jericho** [cake-build/website#1470]
[Contributions](https://cakebuild.net/community/cake-contrib) page should direct people to our GitHub discussions rather than the Gitter channel:

![image](https://user-images.githubusercontent.com/112710/104104739-f3373700-5277-11eb-9ce1-39c23bed74ab.png)

**Comment by pascalberger** [comment]
You mean the [Cake Contributions](https://cakebuild.net/community/cake-contrib) page (not the Thanks page)? Cake-Contrib currently actually still uses Gitter and not GitHub Discussions. We can discuss with maintainers if they prefer moving to GitHub Discussions and if it should be a separate GitHub Discussions or a category in the main Cake GitHub Discussions.

**Comment by Jericho** [comment]
Yes sorry, I meant "Contributions page. Updated my original comment.

**Comment by Jericho** [comment]
The reason I mention this is because it's getting confusing to figure out when to use Gitter and when to use GitHub. I just think we should standardize.

**Comment by pascalberger** [comment]
Agree, but we need to bring this up with Cake-Contrib maintainers first. I'll reach out to them

**Comment by pascalberger** [comment]
Asked [here](https://app.slack.com/client/T4QH7CYJK/C4PTD6RJ8/thread/C4QGVGYTY-1609971894.012100)

**Comment by pascalberger** [comment]
Decision was to got with GitHub Discussions and using a category under the main discussions on the Cake repository since this makes it easier for users to search for questions in a single place.

Category has been created here: https://github.com/cake-build/cake/discussions/categories/extension-q-a

**Comment by pascalberger** [comment]
Link on website will be updated with https://github.com/cake-contrib/Home/pull/72
