### ISSUE TITLE
Frosting: Update docs for rename of CakeHost extension from UseTool to InstallTool

### ISSUE THREAD

**Issue by augustoproiete** [cake-build/website#1504]
Related issues:
- https://github.com/cake-build/cake/pull/3048#pullrequestreview-574882900
- https://github.com/cake-build/cake/issues/3050

**Comment by pascalberger** [comment]
This one is easy since we currently don't have any documentation about it 😄 We have https://github.com/cake-build/website/issues/1216 for adding tool documentation for Frosting.

**Comment by pascalberger** [comment]
We should add it to https://cakebuild.net/docs/getting-started/upgrade though
