### ISSUE TITLE
Feature Request: Search for documentation in the website.

### ISSUE THREAD

**Issue by gep13** [cake-build/website#153]
@bibodha commented on [Fri Sep 09 2016](https://github.com/cake-build/cake/issues/1216)

I would love to be able to search the documentation from the cakebuild.net website. Currently, to search, I have to go to google, type `site:cakebuild.net <search term>`. It would be awesome if we can just have a simple google search input field added to the website as a first iteration and see if it needs to be made better.

**Comment by pascalberger** [comment]
https://cakeissues.net, which is built very similar to this website, has implemented search using https://www.algolia.com/docsearch (see https://github.com/cake-contrib/Cake.Issues.Website/pull/141 for PR implementing it). Something similar could be done for this website.

**Comment by gep13** [comment]
@pascalberger I think that this would be a great addition!

**Comment by pascalberger** [comment]
I applied for docsearch. Will implement this once we got our account setup.
