### ISSUE TITLE
How do you pass parameters to build.cake from build.ps1?

### ISSUE THREAD

**Issue by xclayl** [cake-build/website#169]
My build.cake file has this:

`var version = Argument("build_version", "0.9.0-beta");`

I'm trying to pass the information to build.ps1:

`powershell .\build.ps1 -build_version=%VERSION%`

This doesn't seem to work.  The documentation talks about cake.exe, but that's some internal exe that I don't use directly, right?  

Can you replace the documentation for cake.exe parameters with examples for build.ps1?

**Comment by devlead** [comment]
Is VERSION an environment variable? If so you can use the the [EnvironmentVariable(string)](http://cakebuild.net/api/cake.common/7bef281e/3aa917af) alias.

Otherwise try `-ScriptArgs='--build_version="%VERSION%"'` after build.ps1

**Comment by devlead** [comment]
_note this issue probably better suited for the [cake-build/resources](https://github.com/cake-build/resources)_

**Comment by xclayl** [comment]
The ScriptArgs above didn't work.  It errored with "More than one build script specified."

Also, this didn't work:

```
SET build_version=%1
powershell .\build.ps1 
```

I'll ask the resources repo people and then afterwards come back here to ask to update the documenation once I find out how to do it.

**Comment by xclayl** [comment]
PR added to document how to do this: #182
