### ISSUE TITLE
Repository Link for HipChat addin repository is broken

### ISSUE THREAD

**Issue by Structed** [cake-build/website#172]
The link to the Cake.HipChat addin on the [reference-page](http://cakebuild.net/dsl/hipchat) is broken.

Current link target: https://github.com/cake-contrib/HipChat
Correct link target: https://github.com/cake-contrib/Cake.HipChat

**Comment by Structed** [comment]
I believe I know how to fix it myself, however not totally sure. Guidance is appreciated ;-)

**Comment by gep13** [comment]
@Structed yes, that sounds like the correct approach! 😄
