### ISSUE TITLE
Incorrect documentation for NuGet

### ISSUE THREAD

**Issue by antwilliams** [cake-build/website#180]
As [discussed on Gitter](https://gitter.im/cake-build/cake?at=57fe0cce84f1db0614a27977) a few days ago the documentation for NuGet appears to be incorrect.

All of the NuGet documentation is currently grouped under the Cake.ExtendedNuGet 3rd Party documentation, including the aliases that are included as a core part of Cake. 

The guide is then slightly misleading since it states that you need to use `#addin "Cake.ExtendedNuGet"` to bring in the NuGet functionality.

**Comment by antwilliams** [comment]
Actually this might be related to #51

**Comment by gep13** [comment]
@antwilliams yes, I would say that these are related.

**Comment by daveaglick** [comment]
This issue is superseded by #244 which contains a lot of discussion about how to deal with the underlying problem of addin category collisions.
