### ISSUE TITLE
Allow addins to be marked as pre-release or beta

### ISSUE THREAD

**Issue by phil-scott-78** [cake-build/website#184]
As discussed with @gep13 in this [issue](https://github.com/enkafan/Cake.Mage/issues/2) in one of my repositories, it would be nice if add-ins could be listed but marked as pre-release on the site. My use case is that I have an add-in that definitely falls in the "works on my machine" status. It invokes MAGE.exe for building click-once apps and frankly I'm kind of annoyed we still use click-once so I'm not really going to be spending a ton of time testing every scenario out on it on the weekends.

But it should work. I think others would find value in it, and maybe someone that really loves click-once could test contribute to get it to a 1.0 stage. And the best place for me to get the word out would be the add-in list, but I'd like to set expectations on its current state.

**Comment by daveaglick** [comment]
We can currently mark addins as prerelease in the YAML data for the purpose of downloading the NuGet package. Is this issue about bringing that indication forward to the GUI?

**Comment by devlead** [comment]
@daveaglick that's a good point displaying that it's prerelease under addins makes sense, As we now have the info. Perhaps under addins we even could suggest
```cake
#addin nuget:?package={addin}&prerelease
```
or for non preview
```cake
#addin nuget:?package={addin}
```

Just as nuget.org suggests 
```
Install-Package Newtonsoft.Json -Pre
```
or for non preview
```
Install-Package Newtonsoft.Json
```
