### ISSUE TITLE
Exceptions on site spill stacktrace

### ISSUE THREAD

**Issue by trailmax** [cake-build/website#188]
Exceptions on website are not properly handled:

![2016-10-21 00_09_07-could not find member](https://cloud.githubusercontent.com/assets/3606356/19581134/e1e5d692-9722-11e6-8fc4-ebe37a2d99ad.png)

Exception caused by this url: http://cakebuild.net/api/cake.common.tools.gitversion/84dbc5a7/73c9573a - found the link in Google.

Need to set `customErrors = "On"` in `web.config`.

**Comment by rodius** [comment]
same here 

http://cakebuild.net/api/cake.common.tools.wix/20e371f5/c54d1142

ran accross it few times in the past 5 days

**Comment by devlead** [comment]
FYI we've requested a reindex at google so hopefully they'll comply with that soon.

**Comment by trailmax** [comment]
@devlead I just don't like yellow screens of death with internals on public view - not very good infosec

**Comment by devlead** [comment]
@trailmax agree :) Not had time to fix all issues yet, just moved to new environment. On todo to add proper logging and correct web.config. 
That said site complete source is avail in this repo so not super worried we'll expose any major secrets. But totally agree it should be addressed.

**Comment by devlead** [comment]
Custom errors are now ok and namespaces, types & members that aren't found will get and http not found instead if throwing an exception.

**Comment by rodius** [comment]
301 redirect will fix outdated links

**Comment by devlead** [comment]
@rodius yes, will add that, this was just a quickfix.
