### ISSUE TITLE
XML documentation not always available on website

### ISSUE THREAD

**Issue by trailmax** [cake-build/website#192]
Not all XML documentation is published from addon nugets on the web-site? For example http://cakebuild.net/dsl/yaml have nothing displayed, but it is actually available https://github.com/Redth/Cake.Yaml/blob/master/Cake.Yaml/YamlAliases.cs

Same with SQL Server one: http://cakebuild.net/dsl/sqlserver source: https://github.com/AMVSoftware/Cake.SqlServer/blob/master/src/Cake.SqlServer/SqlServerAliases.cs
And I've checked, the xml file with documentation is available in the nuget

**Comment by gep13** [comment]
@trailmax this is very strange...

When I run the site locally, I see this:

![image](https://cloud.githubusercontent.com/assets/1271146/19644267/b876e9f6-99e6-11e6-9acb-2fbbd209d8b0.png)

However, when I run the actual site, I see this:

![image](https://cloud.githubusercontent.com/assets/1271146/19644288/cf5535ba-99e6-11e6-855d-73b5bfbc3d25.png)

@devlead could this be an issue with not clearing out the local `lib` folder on the website?

**Comment by devlead** [comment]
@gep13 actually site should get a completely new lib folder each build. as we build to a new folder and download nugets and then deploy that folder. Builds only occur on publish though so if nuget updated post publish that might be the issue.

Site was last published on Saturday 6AM UTC, October 22, 2016 when was the nuget package published?

**Comment by patriksvensson** [comment]
No addins have doc comments on both develop and master publish as far as i can see.

**Comment by gep13** [comment]
@patriksvensson there is at least one 😄 http://cakebuild.net/dsl/gem

**Comment by gep13** [comment]
@devlead Saturday 22nd: https://www.nuget.org/packages/Cake.SqlServer/

**Comment by gep13** [comment]
@devlead although previous version from September 11th also had XML comments.

**Comment by gep13** [comment]
@patriksvensson ah, hold on, that one I linked to is built in...

**Comment by gep13** [comment]
Cake.Gitter has comments and summary: http://cakebuild.net/api/cake.gitter/3c92abaa/aecf0887

**Comment by devlead** [comment]
Found issue not all files seems to have been published, don't know why, investigating.

**Comment by gep13** [comment]
@devlead thanks for looking into this!

**Comment by devlead** [comment]
Tracked down to Azure nuget skip XML docs, reason only some are affected seems to be if they got valid lib/framework structure.
Will do some testing then push a fix.

**Comment by devlead** [comment]
@trailmax @cake-build/team tracked down issue to environment variables set in Azure changing nuget behavior and cached nuget packages being used despite no cache specified.

New web is now published and docs should be visible
![image](https://cloud.githubusercontent.com/assets/1647294/19681006/11e8a81e-9aa8-11e6-93d3-4508373f9272.png)

**Comment by trailmax** [comment]
@devlead Awesome! thank you!
