### ISSUE TITLE
Add the three new email addins to the list of addins

### ISSUE THREAD

**Issue by Jericho** [cake-build/website#196]
Three new addins were released on 10/30/16 but are missing from the list of addins on the cake website. The new addins are:
- Cake.Email
- Cake.CakeMail
- Cake.SendGrid

**Comment by gep13** [comment]
@Jericho are you planning on creating a PR for this? Otherwise I will take care of it tonight.

**Comment by Jericho** [comment]
Doing it right now...

**Comment by gep13** [comment]
@Jericho this is now live on the site:

http://cakebuild.net/addins/category/email
