### ISSUE TITLE
UI bug 1600x900

### ISSUE THREAD

**Issue by Marusyk** [cake-build/website#2011]
I cannot see the menu item above Fundamentals.

![image](https://user-images.githubusercontent.com/9221694/118196869-6a631e80-b456-11eb-9853-4d8fd007efc2.png)

**Comment by augustoproiete** [comment]
I was able to repro on Chrome v90.0.4430.93 on MacOS.

The issue happens when the right sidebar with the "Edit Content" link becomes visible.

![image](https://user-images.githubusercontent.com/177608/118197501-771b4e80-b425-11eb-8cc8-4792e3897a92.png)

**Comment by pascalberger** [comment]
Yes, this is an issue with smaller resolutions when top level nvigation breaks into two rows as we don't have any responsiveness impelemented for them currently.

**Comment by saurabhhere** [comment]
Just add `margin-top: 30px;` in `.main-sidebar` inside your `AdminLTE.css` file and you will be good to go for every resolutions.
Or if you don't want to add margin in normal view just use this inside media-queries :)

**Comment by saurabhhere** [comment]
For that, I have to set up this locally to test the changes. I guess it would be better if you can test it on your setup locally and update me if it works or not.
Also, I don't have any issue if anybody wants to open PR for this.
