### ISSUE TITLE
Add new Cake.MsDeploy to plugin 

### ISSUE THREAD

**Issue by louisfischer** [cake-build/website#203]
Request to add a new Cake.MsDeploy Add-in to the list of available plugin s on the cake website.

https://github.com/louisfischer/Cake.MsDeploy

**Comment by gep13** [comment]
@louisfischer would you be in a position to make a PR to get this added?

Perhaps best to wait until we move the addin to the Cake Contrib Organisation though.

**Comment by louisfischer** [comment]
Yes i can do a pull request to get it added. I will work on it while the repo is being transferred. 
After the repo has been transferred, i will submit the pull request for review

**Comment by louisfischer** [comment]
#204 Added to  cake website. Closing issue.
