### ISSUE TITLE
Remove Cake.Watch_Advance

### ISSUE THREAD

**Issue by pascalberger** [cake-build/website#2116]
[Cake.Watch_Advance](https://cakebuild.net/extensions/cake-watch_advance/) seems to be a fork of [Cake.Watch](https://cakebuild.net/extensions/cake-watch/). We should remove it from website and blacklist in Addin discoverer.

**Comment by pascalberger** [comment]
Addins are updated by a tool called addin discoverer, which maintains the extension metadata used to build the website at https://github.com/cake-build/website/tree/master/extensions.

For this issue I don't see much advance to have Cake.Watch_Advance listed, as it is a fork of Cake.Watch, which also targets a later version of Cake and doesn't come with proper metadata and documentation.

To fix this issue two things are required:

- Add `Cake.Watch_Advance` to addin discoverer blacklist at https://github.com/cake-contrib/Cake.AddinDiscoverer/blob/develop/Source/Cake.AddinDiscoverer/exclusionlist.json
- Once this is merged and a new version of addin discoverer has been released the addin can be removed from website by deleting the file https://github.com/cake-build/website/blob/master/extensions/Cake.Watch_Advance.yml

**Comment by TomerPacific** [comment]
Hi @pascalberger , leaving a comment here per your recommendation.

**Comment by TomerPacific** [comment]
@pascalberger , I have opened a relevant PR in the appropriate repository. I saw that the one check has failed due to:

```
Executing: "artifacts/Publish/Cake.AddinDiscoverer.exe" -t "./artifacts/" -u "cake-contrib-bot" -p "[REDACTED]" -m -e
The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'password')
```

Should there be any changes made except the one you mentioned?

Also, could you mark this issue as hacktoberfest-accepted?

**Comment by Jericho** [comment]
@TomerPacific don't worry about the build failure. It's simply caused by the fact that a PR build on AppVeyor does not have access to the same environment variables as a "normal" build. Therefore expected variables, such as "password" for example, are blank when the build script attempts to run the Addin Discoverer which causes the execution to fail. But rest assured that it doesn't mean there's anything wrong with the change you are submitting. I'll improve the build script to avoid this failure in the future.

**Comment by Jericho** [comment]
On detail to note: the discoverer will take care of deleting the yml file when I publish the update, so no need to manually delete it

**Comment by Jericho** [comment]
Addin discoverer has been updated and new version published. As promised, it automatically deleted the yml file (pending approval, of course). See: https://github.com/cake-build/website/issues/2209

**Comment by pascalberger** [comment]
@TomerPacific Thanks for taking care of this 👍
