### ISSUE TITLE
Missing "params" in documentation

### ISSUE THREAD

**Issue by devlead** [cake-build/website#215]
@pmiossec commented on [Wed Nov 02 2016](https://github.com/cake-build/cake/issues/1335)

If you look at this doc, http://cakebuild.net/api/cake.git/8654684f/66b43fe5, the `params` key word is missing and so the doc is misleading :(

It seems to be an issue with the generator...

/ cc @devlead (I don't know if I should create the issue here or in the https://github.com/WCOMAB/Cake_Git repository . But in the source code, it seems good: https://github.com/WCOMAB/Cake_Git/blob/master/src/Cake.Git/GitAliases.Remove.cs#L20 )

---

@devlead commented on [Sun Nov 13 2016](https://github.com/cake-build/cake/issues/1335#issuecomment-260198660)

Params is an attribute, it's not related to the addin but rather the website documentation generation, so I'll move the issue to website repo.

**Comment by daveaglick** [comment]
FWIW, it looks like the new generator outputs the `params` keyword for the syntax examples, but the resulting array type isn't being recognized in the parameter list table. I'll have to take a closer look at this - if it gets resolved in the current site please keep this ticket open as a reminder to verify once the new one is ready.

**Comment by daveaglick** [comment]
It's a little better in the new docs. The `params` keyword and array type is being output in the syntax example so there's at least some clue that it's there. However, the type still isn't recognized in the [list of parameters](http://cakebuild.net/api/Cake.Git/GitAliases/E1A15CFA#Parameters). Tracking in https://github.com/Wyamio/Wyam/issues/407.

**Comment by daveaglick** [comment]
This is now fixed in Wyam. Any params parameters will correctly report their array type. Leaving open until the next Wyam release, republish, and verification in production.

**Comment by daveaglick** [comment]
Verified as fixed.
