### ISSUE TITLE
Improve Overwiew->Requirements documentation

### ISSUE THREAD

**Issue by abeggchr** [cake-build/website#219]
Please add more documentation on what to install on Linux and Mac. I suggest a structure like:

1. Windows
1.1. .NET Core
1.2. Full Framework
2. Linux
2.1. .NET Core
2.2. Mono
3. OS X
3.1. .NET Core
3.2. Mono

I took the wrong conclusion from the current ["Overview"->"Requirements"](https://github.com/cake-build/website/blob/develop/src/Cake.Web/App_Data/docs/overview/requirements.md) that in order to run a cake script on Linux, you only need .NET core. Turns out, that using "mono" is hard-coded in the `build.sh` script. 

On a second sight, the hint for [Cake.CoreCLR](https://www.nuget.org/packages/Cake.CoreCLR) does not work for me - doesn't seem to fit into the rest of the "getting started" page (and I don't know how to use it #newbie).

See "The Linux experience" on the bottom of [this page](https://github.com/r3dDoX/todomvc-vanilla-es6/blob/cake/README.md)

**Comment by pascalberger** [comment]
Documentation has been updated. The different runnes with their requirements are now documented [here](https://cakebuild.net/docs/getting-started/running-cake-scripts) with the different bootstrapping options documented [here](https://cakebuild.net/docs/getting-started/bootstrapping-scripts).
