### ISSUE TITLE
Add documentation for optional parameter support

### ISSUE THREAD

**Issue by kcamp** [cake-build/website#227]
As part of the work done for cake-build/cake#1166 - Support optional parameters on alias methods - documentation for the same was requested.  Creating this issue/request to track changes against.

**Comment by kcamp** [comment]
@gep13 - The Alias page seems like the best fit for this, as well? http://cakebuild.net/docs/fundamentals/aliases

**Comment by gep13** [comment]
@kcamp yes, I think that this would make sense.

@cake-build/team thoughts?

**Comment by gep13** [comment]
Looks like this issue has already been addressed.
