### ISSUE TITLE
Change syntax highlighter

### ISSUE THREAD

**Issue by devlead** [cake-build/website#23]
Currently XML isnt't displayed correctly, see [contributing/documentation](http://cakebuild.net/docs/contributing/documentation)  as an example.

Suggest trying [highlight.js](https://highlightjs.org/)

**Comment by gep13** [comment]
:+1: on highlight.js.  Not used it before, but looking at the demo, it looks very cool!

**Comment by patriksvensson** [comment]
I approve of this issue. :+1:
