### ISSUE TITLE
Documentation: broken string wrapping

### ISSUE THREAD

**Issue by ChrisMaddock** [cake-build/website#239]
The table isn't wrapping correctly on this page. http://cakebuild.net/api/cake.core/f005e67e

Here's a screenshot of what I was seeing in case things change - this is Chrome v55.0.2883.87 m

![image](https://cloud.githubusercontent.com/assets/4837132/21454820/6e838d52-c913-11e6-980e-cd09f41650b3.png)

**Comment by devlead** [comment]
@daveaglick is assisting in rewriting the site with pr #236, believe this an allot other issues will be sorted with the new site.

**Comment by ChrisMaddock** [comment]
Cool - new site look awesome! Nice one @daveaglick! 😄

**Comment by devlead** [comment]
Confirmed fixed with new site.
