### ISSUE TITLE
Add supported help XML tags to contributing/documentation

### ISSUE THREAD

**Issue by devlead** [cake-build/website#24]
Add supported help comment XML tags to  [contributing/documentation](http://cakebuild.net/docs/contributing/documentation)

See cake-build/cake#491 for supported tags info.

**Comment by devlead** [comment]
This is sorted right?

**Comment by gep13** [comment]
@devlead Personally, I still think we need to come up with a recommendation, to what "should" be included in a Summary documentation section, i.e. include `<see>` with external links, to either source code/help documentation for associated tool/extension.

Once we know what that recommendation is, we can add it to the documentation page, and then add to all internal aliases, and recommend external addin's do the same.

**Comment by daveaglick** [comment]
Wyam supports all [recommended XML comment tags](https://msdn.microsoft.com/en-us/library/5ast78ax.aspx) so the question now is one of convention. What tags would you expect or like to see from addin authors when documenting their addins?

**Comment by devlead** [comment]
Issue covers both addins and core, perhaps it's a matter what's missing from
http://cakebuild.net/docs/contributing/documentation
?
@cake-build/team thoughts?

**Comment by gep13** [comment]
Yes, this issue was really about providing guidance for what a "good" summary section looks like.

I tend to use something like this:

![image](https://cloud.githubusercontent.com/assets/1271146/22222359/72d08d70-e1ae-11e6-83d9-ac9a2b037b4e.png)

And this issue was really about getting that into our documentation so that other places could do somethign similar as well for consistency.

**Comment by devlead** [comment]
An thought tough, could parts of code like that be auto generated for addins? Something like what I inferred in issue #184?

**Comment by pascalberger** [comment]
Instructions how to add an addin to the build are now part of the addin details page. For creating best practices how to write documentation I've created https://github.com/cake-build/website/issues/1241.
