### ISSUE TITLE
Add write up about splitting cake files into different nuget packages

### ISSUE THREAD

**Issue by gep13** [cake-build/website#25]
As discussed here:

https://github.com/cake-build/cake/issues/488

I think a great addition to the site would be a write up on how to break a build script into different constituent parts, and then construct the lego pieces required for a particular build.

**Comment by danbarua** [comment]
👍 for this - most of the examples I can find online are 'hello world'

**Comment by pascalberger** [comment]
Closed as duplicate of #932
