### ISSUE TITLE
Add write up about centrally managing build script

### ISSUE THREAD

**Issue by gep13** [cake-build/website#26]
As discussed here:

https://github.com/cake-build/cake/issues/492

We should provide a write up, perhaps in the form of a `how-to` article, on a suggested best practice for having a central build.cake file that you can consume from multiple projects.

This will be related to this article https://github.com/cake-build/website/issues/25, but tackle a slightly different problem.

**Comment by MonDeveloper** [comment]
+1

**Comment by pascalberger** [comment]
Fixed with #1222
