### ISSUE TITLE
Rewrite "Getting started" guide

### ISSUE THREAD

**Issue by patriksvensson** [cake-build/website#27]
The current getting started guide is good and all, but I think the guide "Setting up a new project" is much simpler to really get started.

I think the "Setting up a new project" should be the "Getting started" guide, and instead add some documentation how to write a cake script that can be a nice follow up to the "Getting started" guide.

**Comment by pascalberger** [comment]
Getting startet documentation has been updated and an updated "Setting up a new project" page is now linked from the landing page.
