### ISSUE TITLE
Change in arrow alignment inside this UI Circle

### ISSUE THREAD

**Issue by Dishank25S** [cake-build/website#2735]
Change in arrow alignment inside this UI Circle , This will please the users and won't trigger their ADHD

**Comment by Dishank25S** [comment]
![image](https://github.com/cake-build/website/assets/99533410/4f16815c-2c64-47d5-8d61-989eecf0128d)

**Comment by VaniThapar** [comment]
I am interested in solving this issue, can you please assign it to me? @Dishank25S

**Comment by Royal-Dragon** [comment]
which page is this one

**Comment by pascalberger** [comment]
Closing as this does not seem to be an issue related to this repository or otherwise please mention what and where the actual is @Dishank25S Dishank25S
