### ISSUE TITLE
Old download urls are broken

### ISSUE THREAD

**Issue by Redth** [cake-build/website#275]
On the old website we had redirects for:

 - http://cakebuild.net/bootstrapper/packages
 - http://cakebuild.net/bootstrapper/osx
 - http://cakebuild.net/bootstrapper/windows

Which of course now exist at:
 - http://cakebuild.net/download/bootstrapper/packages
 - http://cakebuild.net/download/bootstrapper/osx
 - http://cakebuild.net/download/bootstrapper/windows

These lost redirects might cause issues for existing users, and should be added back, and perhaps monitored for their usage to see when it's suitable to drop them.

**Comment by devlead** [comment]
That's an easy fix, I'll fix asap and ping back her when fixed.

**Comment by devlead** [comment]
Broken no mord 😉
