### ISSUE TITLE
Figure out which version of Cake Addin's are targeting

### ISSUE THREAD

**Issue by gep13** [cake-build/website#299]
When parsing the addins, is it possible to figure out what version of Cake they are targeting? I think this information would be useful to put on the site, as this won't be the only time that we make a change where addins only support a particular cake version.

**Comment by gep13** [comment]
Also, I was thinking that it would be good to know if it was targetting .Net Core or not.

Adding this information into the Addin's page I think would be useful.

**Comment by pascalberger** [comment]
Mockup for a new extension page which would show supported Cake versions for each extension (addin, module, recipe): https://github.com/cake-build/website/issues/1096#issuecomment-711096108

**Comment by Jericho** [comment]
FYI the addin discoverer already gathers this information. Let me know if there's a way to output the data in a way that can be consumed by the process that generates the docs.

**Comment by pascalberger** [comment]
What I would like to have is the supported Cake versions of the latest versions of an addin be displayed on the addin details page: 

![image](https://user-images.githubusercontent.com/2190718/97115961-7c6bb280-16fa-11eb-9f29-b6423d8bd739.png)
 
This would be equals to the version of Cake which the addin is built against until the next potential breaking change or latest version. Some examples (at that time `0.38.5` is the latest version):

| Target version | Information shown on website |
|-|-|
| 0. 33.0 | 0.33.0 - 0.38.5 |
| 0. 35.0 | 0.35.0 - 0.38.5 |
| 0. 30.0 | 0.30.0 - 0.32.1 |

I see some possible ways how to get there:

1. Analyze Cake version targeted by an addin while building website, retrieve available Cake versions and based on this determine string to show
2. Have the target version for every addin the addins yml file. Determine string to show while building website. Addin discoverer keeps target version up to date.
3. Have the full string as part of the addins yml file. Addin discoverer determines string and keeps yml files up to date.

IMHO we should either go all in with regards to addin discoverer (number 3) or do everything as part of the website build (number 1). Since Cake version targeted by a specific version of an addin is static and addin update is already handled by addin discoverer I would prefer to go with version 3.

@Jericho Would number 3 something which addin discoverer would be able to provide?

**Comment by Jericho** [comment]
Number 2 would be trivial for me to do. I’m sure I can figure out a way to achieve number 3 as well but I just need to invest a little bit of time to figure out it out.

**Comment by Jericho** [comment]
I propose the following changes in yaml generated by discoverer:

- add the version of the NuGet package that was analyzed (I’m guessing this info would be useful to display on web site)
- add the version of Cake targeted (e.g.: 0.34.0)
- add the **range** of Cake versions compatible with this version of the addin. Syntax TBD.

**Comment by pascalberger** [comment]
> * add the version of the NuGet package that was analyzed (I’m guessing this info would be useful to display on web site)

We already read the version (and display it, e.g. https://cakebuild.net/extensions/cake-7zip/). So no need for this.

> * add the version of Cake targeted (e.g.: 0.34.0)

No need for this if the next point is implemented.

> * add the **range** of Cake versions compatible with this version of the addin. Syntax TBD.

This is the part which we need. From the [comment](https://github.com/cake-build/website/issues/299#issuecomment-716194086) above how this should look like:

> This would be equals to the version of Cake which the addin is built against until the next potential breaking change or latest version. Some examples (at that time `0.38.5` is the latest version):
>
>| Target version | Information shown on website |
>|-|-|
>| 0. 33.0 | 0.33.0 - 0.38.5 |
>| 0. 35.0 | 0.35.0 - 0.38.5 |
>| 0. 30.0 | 0.30.0 - 0.32.1 |

If we choose version 3 from above. I can go ahead an add the required attribute to the yaml file (https://github.com/pascalberger/website/commit/03e36fdc90516c87ed9b193eb5ae5ef8989f8e98).

**Comment by Jericho** [comment]
> We already read the version (and display it, e.g. https://cakebuild.net/extensions/cake-7zip/). So no need for this.

But how do you know the version you read corresponds to the version that was analyzed?

For instance, the latest version of a given addin could have changed between the last scheduled discoverer and the time when you build the documentation. This means the info in yaml file maintained by the discoverer might not match the version of an addin you are documenting. If your process is going to rely on info generated by the discoverer, we need to ensure that we are in sync with the version of the NuGet packages.

**Comment by pascalberger** [comment]
> > * add the **range** of Cake versions compatible with this version of the addin. Syntax TBD.
> 
> This is the part which we need. From the [comment](https://github.com/cake-build/website/issues/299#issuecomment-716194086) above how this should look like:
> 
> > This would be equals to the version of Cake which the addin is built against until the next potential breaking change or latest version. Some examples (at that time `0.38.5` is the latest version):
> > 
> > 
> > 
> > Target version
> > Information shown on website
> > 
> > 
> > 
> > 
> > 0. 33.0
> > 0.33.0 - 0.38.5
> > 
> > 
> > 0. 35.0
> > 0.35.0 - 0.38.5
> > 
> > 
> > 0. 30.0
> > 0.30.0 - 0.32.1

Some points to take into consideration: 
* When an addin targets a different version of Cake, this will be automatically be updated by addin discoverer and handled automatically
* When a new version of Cake is released information for addins which target latest API version will be outdated. To solve this I would suggest to just write `latest` instead of the effective version (e.g. `0.33.0 - latest`). We still can improve on this once we read the latest Cake version and replace `latest` with the effective version.

**Comment by pascalberger** [comment]
> > We already read the version (and display it, e.g. https://cakebuild.net/extensions/cake-7zip/). So no need for this.
> 
> But how do you know the version you read corresponds to the version that was analyzed?
> 
> For instance, the latest version of a given addin could have changed between the last scheduled discoverer and the time when you build the documentation. This means the info in yaml file maintained by the discoverer might not match the version of an addin you are documenting. If your process is going to rely on info generated by the discoverer, we need to ensure that we are in sync with the version of the NuGet packages.

Since addin discoverer runs scheduled, this should only be an issue for a limited period of time. We're running a static generated site, which can be slightly outdated on several occassions (e.g. search index not yet synced with page content, latest addin release changing assembly name or repository before addin discoverer updates it, etc). I'm perfectly happy with this. To solve this, solution would be to not rely on any external tool like addin discoverer and implement everything in the website build process, which would increase build process (and build time) significant.

**Comment by Jericho** [comment]
Had a conversation with @pascalberger and we agreed to the following:

- AddinDiscoverer will maintain a new attribute in the YAML file called `TargetCakeVersion`
- The value will be the version of Cake.Core and/or Cake.Common referenced by this addin
- If an addin targets Cake.Core version A and Cake.Common version B, the smallest version will be used. (this is an edge case. I checked and no addin currently does this)

**Comment by augustoproiete** [comment]
@Jericho / @pascalberger Are either of you working on this one already? If not I can take it.

**Comment by pascalberger** [comment]
@augustoproiete I have it on my list, but not actively working on it. So more than happy if you take it. Idea is that we enhance the extension YAML flies with an entry for the exact version of Cake an extension targets. This field can be kept up to date through AddinDiscoverer. 

My idea for the website was to not only show the Cake version, but the range of Cake versions an extension is compatible with, based on addin compatibility of Cake (see https://user-images.githubusercontent.com/2190718/96355764-bbd84480-10e5-11eb-908b-284925bc582c.png for a mockup). This would require some additional logic in the website code.

**Comment by Jericho** [comment]
AddinDisco is ready, I just haven't published the new version. Here's what the content of a YAML file will look like:
![image](https://user-images.githubusercontent.com/112710/100633415-12978780-32fc-11eb-8daa-b12b1255463b.png)

Normally we prefer each change to be in a separate issue+PR so we can accept or reject or discuss each one. But in this case we would be flooded with 300+ issues (and their corresponding PRs) in batches of 75 (to avoid triggering GitHub abuse detection) so I think it makes sense to exceptionally group 75 of these changes in a single issue and its corresponding PR so I'm working on that.

**Comment by pascalberger** [comment]
Cake version is now set in all addin metadata. I extended `ExtensionSpec` class, but didn't to anything with the data yet.

@augustoproiete I assigned this issues to you, if still OK for you to give this a try

**Comment by augustoproiete** [comment]
Thanks @pascalberger. I'll take a stab on it.

**Comment by augustoproiete** [comment]
@pascalberger @Jericho 

Gents, I have a branch ready for a PR and wanted to confirm the ranges that we want to use for add-ins targeting `Cake.Core` and/or `Cake.Common` < `0.30.0`.

I understand from the above that the AddinDiscoverer sets `TargetCakeVersion` to `Min(Version(Cake.Core), Version(Cake.Common))` so I put together a distinct list of all possible values as of this writing and what my logic would assign to `SupportedCakeVersions` and tried to match with all possible versions of the [**Cake** nuget package](https://www.nuget.org/packages/Cake/).

- For `TargetCakeVersion` >= `0.30.0` it's using @pascalberger's example ranges above
- For `TargetCakeVersion` < `0.30.0` it's using `[major.minor.0 - major.minor.*]` i.e. assumes compat break every bump of either `major` or `minor` - **Does this make sense or do we want to simplify these ranges?**

| TargetCakeVersion | SupportedCakeVersions |
|:---:|:---:|
| 1.0.0-rc0001 | 1.0.0-rc0001 |
| 0.38.5 | 0.35.0 - 0.38.5 |
| 0.38.4 | 0.35.0 - 0.38.5 |
| 0.38.3 | 0.35.0 - 0.38.5 |
| 0.38.2 | 0.35.0 - 0.38.5 |
| 0.38.1 | 0.35.0 - 0.38.5 |
| 0.38.0 | 0.35.0 - 0.38.5 |
| 0.37.0 | 0.35.0 - 0.38.5 |
| 0.36.0 | 0.35.0 - 0.38.5 |
| 0.35.0 | 0.35.0 - 0.38.5 |
| 0.34.1 | 0.33.0 - 0.38.5 |
| 0.34.0 | 0.33.0 - 0.38.5 |
| 0.33.0 | 0.33.0 - 0.38.5 |
| 0.32.1 | 0.30.0 - 0.32.1 |
| 0.32.0 | 0.30.0 - 0.32.1 |
| 0.31.0 | 0.30.0 - 0.32.1 |
| 0.30.0 | 0.30.0 - 0.32.1 |
| 0.29.0 | 0.29.0 |
| 0.28.1 | 0.28.0 - 0.28.1 |
| 0.28.0 | 0.28.0 - 0.28.1 |
| 0.27.2 | 0.27.0 - 0.27.2 |
| 0.27.1 | 0.27.0 - 0.27.2 |
| 0.27.0 | 0.27.0 - 0.27.2 |
| 0.26.1 | 0.26.0 - 0.26.1 |
| 0.26.0 | 0.26.0 - 0.26.1 |
| 0.25.0 | 0.25.0 |
| 0.24.0 | 0.24.0 |
| 0.23.0 | 0.23.0 |
| 0.22.2 | 0.22.0 - 0.22.2 |
| 0.22.1 | 0.22.0 - 0.22.2 |
| 0.22.0 | 0.22.0 - 0.22.2 |
| 0.21.1 | 0.21.0 - 0.21.1 |
| 0.21.0 | 0.21.0 - 0.21.1 |
| 0.20.0 | 0.20.0 |
| 0.19.5 | 0.19.0 - 0.19.5 |
| 0.19.4 | 0.19.0 - 0.19.5 |
| 0.19.3 | 0.19.0 - 0.19.5 |
| 0.19.2 | 0.19.0 - 0.19.5 |
| 0.19.1 | 0.19.0 - 0.19.5 |
| 0.19.0 | 0.19.0 - 0.19.5 |
| 0.18.0 | 0.18.0 |
| 0.17.0 | 0.17.0 |
| 0.16.2 | 0.16.0 - 0.16.2 |
| 0.16.1 | 0.16.0 - 0.16.2 |
| 0.16.0 | 0.16.0 - 0.16.2 |
| 0.15.2 | 0.15.0 - 0.15.2 |
| 0.15.1 | 0.15.0 - 0.15.2 |
| 0.15.0 | 0.15.0 - 0.15.2 |
| 0.14.0 | 0.14.0 |
| 0.13.0 | 0.13.0 |
| 0.12.0 | 0.12.0 |
| 0.11.0 | 0.11.0 |
| 0.10.1 | 0.10.0 - 0.10.1 |
| 0.10.0 | 0.10.0 - 0.10.1 |
| 0.9.0 | 0.9.0 |
| 0.8.0 | 0.8.0 |
| 0.7.0 | 0.7.0 |
| 0.6.4 | 0.6.0 - 0.6.4 |
| 0.6.3 | 0.6.0 - 0.6.4 |
| 0.6.2 | 0.6.0 - 0.6.4 |
| 0.6.1 | 0.6.0 - 0.6.4 |
| 0.6.0 | 0.6.0 - 0.6.4 |
| 0.5.5 | 0.5.0 - 0.5.5 |
| 0.5.4 | 0.5.0 - 0.5.5 |
| 0.5.3 | 0.5.0 - 0.5.5 |
| 0.5.2 | 0.5.0 - 0.5.5 |
| 0.5.1 | 0.5.0 - 0.5.5 |
| 0.5.0 | 0.5.0 - 0.5.5 |
| 0.4.3 | 0.4.0 - 0.4.3 |
| 0.4.2 | 0.4.0 - 0.4.3 |
| 0.4.1 | 0.4.0 - 0.4.3 |
| 0.4.0 | 0.4.0 - 0.4.3 |
| 0.3.2 | 0.3.2 |
| 0.2.2 | 0.2.0 - 0.2.2 |
| 0.2.1 | 0.2.0 - 0.2.2 |
| 0.2.0 | 0.2.0 - 0.2.2 |
| 0.1.34 | 0.1.0 - 0.1.34 |
| 0.1.33 | 0.1.0 - 0.1.34 |
| 0.1.32 | 0.1.0 - 0.1.34 |
| 0.1.30 | 0.1.0 - 0.1.34 |
| 0.1.29 | 0.1.0 - 0.1.34 |
| 0.1.28 | 0.1.0 - 0.1.34 |
| 0.1.27 | 0.1.0 - 0.1.34 |
| 0.1.26 | 0.1.0 - 0.1.34 |
| 0.1.25 | 0.1.0 - 0.1.34 |
| 0.1.24 | 0.1.0 - 0.1.34 |
| 0.1.23 | 0.1.0 - 0.1.34 |
| 0.1.22 | 0.1.0 - 0.1.34 |
| 0.1.21 | 0.1.0 - 0.1.34 |
| 0.1.20 | 0.1.0 - 0.1.34 |
| 0.1.19 | 0.1.0 - 0.1.34 |
| 0.1.18 | 0.1.0 - 0.1.34 |
| 0.1.17 | 0.1.0 - 0.1.34 |
| 0.1.16 | 0.1.0 - 0.1.34 |
| 0.1.15 | 0.1.0 - 0.1.34 |
| 0.1.14 | 0.1.0 - 0.1.34 |

**Comment by pascalberger** [comment]
@augustoproiete Ranges are defined by the [LatestPotentialBreakingChange](https://github.com/cake-build/cake/blob/develop/src/Cake.Core/Constants.cs#L12) (Or LatestBreakingChange in earlier versions) defined in Cake. These are the versions of Cake with potential breaking API for addins:

* 1.0.0
* 0.33.0
* 0.28.0
* 0.26.0
* 0.22.0
* 0.16.0

So an addin targeting 0.23.0 is compatible with 0.23.0 - 0.25.0, an addin targetting 0.26.0 is compatible with 0.26.0 - 0.27.2, and so on. Before 0.16.0 Cake hadn't had any check. Therefore I would suggest to just use the version it builds against: An addin building against Cake 0.13.0 should output 0.13.0.

Going forward we can build on top of this, by either defining a minimum version to have addins listed on the website, or marking outdated addins. I'll create another issue for this.

**Comment by pascalberger** [comment]
An addition: For addins building against anything before Cake 0.16.0, your logic mentioned above (compatible with any version with the same major & minor version) would actually be more accurate. But if this adds more complexity I would ignore it, since these addins are *really* old.

**Comment by augustoproiete** [comment]
Thanks @pascalberger. This is the compatibility range lookup I came up with based on your comments above:

| Cake Version Compat. Range<br> `[minVersion inclusive, maxVersion exclusive)` |
|:---:|
| [1.0.0, ) |
| [0.33.0, 1.0.0) |
| [0.28.0, 0.33.0) |
| [0.26.0, 0.28.0) |
| [0.22.0, 0.26.0) |
| [0.16.0, 0.22.0) |
| [0.15.0, 0.16.0) |
| [0.14.0, 0.15.0) |
| [0.13.0, 0.14.0) |
| [0.12.0, 0.13.0) |
| [0.11.0, 0.12.0) |
| [0.10.0, 0.11.0) |
| [0.9.0, 0.10.0) |
| [0.8.0, 0.9.0) |
| [0.7.0, 0.8.0) |
| [0.6.0, 0.7.0) |
| [0.5.0, 0.6.0) |
| [0.4.0, 0.5.0) |
| [0.3.0, 0.4.0) |
| [0.2.0, 0.3.0) |
| [0.1.0, 0.2.0) |
| [0.0.0, 0.1.0) |

**Exception to the rule**: Add-ins targeting pre-release versions of Cake are pinned to the specific pre-release version they target.

Using the reference table above, all possible versions that add-ins can target resolves to this:

| TargetCakeVersion | SupportedCakeVersions |
|:---:|:---:|
| 1.0.0-rc0001 | 1.0.0-rc0001 |
| 0.38.5 | 0.38.5 |
| 0.38.4 | 0.38.4 - 0.38.5 |
| 0.38.3 | 0.38.3 - 0.38.5 |
| 0.38.2 | 0.38.2 - 0.38.5 |
| 0.38.1 | 0.38.1 - 0.38.5 |
| 0.38.0 | 0.38.0 - 0.38.5 |
| 0.37.0 | 0.37.0 - 0.38.5 |
| 0.36.0 | 0.36.0 - 0.38.5 |
| 0.35.0 | 0.35.0 - 0.38.5 |
| 0.34.1 | 0.34.1 - 0.38.5 |
| 0.34.0 | 0.34.0 - 0.38.5 |
| 0.33.0 | 0.33.0 - 0.38.5 |
| 0.32.1 | 0.32.1 |
| 0.32.0 | 0.32.0 - 0.32.1 |
| 0.31.0 | 0.31.0 - 0.32.1 |
| 0.30.0 | 0.30.0 - 0.32.1 |
| 0.29.0 | 0.29.0 - 0.32.1 |
| 0.28.1 | 0.28.1 - 0.32.1 |
| 0.28.0 | 0.28.0 - 0.32.1 |
| 0.27.2 | 0.27.2 |
| 0.27.1 | 0.27.1 - 0.27.2 |
| 0.27.0 | 0.27.0 - 0.27.2 |
| 0.26.1 | 0.26.1 - 0.27.2 |
| 0.26.0 | 0.26.0 - 0.27.2 |
| 0.25.0 | 0.25.0 |
| 0.24.0 | 0.24.0 - 0.25.0 |
| 0.23.0 | 0.23.0 - 0.25.0 |
| 0.22.2 | 0.22.2 - 0.25.0 |
| 0.22.1 | 0.22.1 - 0.25.0 |
| 0.22.0 | 0.22.0 - 0.25.0 |
| 0.21.1 | 0.21.1 |
| 0.21.0 | 0.21.0 - 0.21.1 |
| 0.20.0 | 0.20.0 - 0.21.1 |
| 0.19.5 | 0.19.5 - 0.21.1 |
| 0.19.4 | 0.19.4 - 0.21.1 |
| 0.19.3 | 0.19.3 - 0.21.1 |
| 0.19.2 | 0.19.2 - 0.21.1 |
| 0.19.1 | 0.19.1 - 0.21.1 |
| 0.19.0 | 0.19.0 - 0.21.1 |
| 0.18.0 | 0.18.0 - 0.21.1 |
| 0.17.0 | 0.17.0 - 0.21.1 |
| 0.16.2 | 0.16.2 - 0.21.1 |
| 0.16.1 | 0.16.1 - 0.21.1 |
| 0.16.0 | 0.16.0 - 0.21.1 |
| 0.15.2 | 0.15.2 |
| 0.15.1 | 0.15.1 - 0.15.2 |
| 0.15.0 | 0.15.0 - 0.15.2 |
| 0.14.0 | 0.14.0 |
| 0.13.0 | 0.13.0 |
| 0.12.0 | 0.12.0 |
| 0.11.0 | 0.11.0 |
| 0.10.1 | 0.10.1 |
| 0.10.0 | 0.10.0 - 0.10.1 |
| 0.9.0 | 0.9.0 |
| 0.8.0 | 0.8.0 |
| 0.7.0 | 0.7.0 |
| 0.6.4 | 0.6.4 |
| 0.6.3 | 0.6.3 - 0.6.4 |
| 0.6.2 | 0.6.2 - 0.6.4 |
| 0.6.1 | 0.6.1 - 0.6.4 |
| 0.6.0 | 0.6.0 - 0.6.4 |
| 0.5.5 | 0.5.5 |
| 0.5.4 | 0.5.4 - 0.5.5 |
| 0.5.3 | 0.5.3 - 0.5.5 |
| 0.5.2 | 0.5.2 - 0.5.5 |
| 0.5.1 | 0.5.1 - 0.5.5 |
| 0.5.0 | 0.5.0 - 0.5.5 |
| 0.4.3 | 0.4.3 |
| 0.4.2 | 0.4.2 - 0.4.3 |
| 0.4.1 | 0.4.1 - 0.4.3 |
| 0.4.0 | 0.4.0 - 0.4.3 |
| 0.3.2 | 0.3.2 |
| 0.2.2 | 0.2.2 |
| 0.2.1 | 0.2.1 - 0.2.2 |
| 0.2.0 | 0.2.0 - 0.2.2 |
| 0.1.34 | 0.1.34 |
| 0.1.33 | 0.1.33 - 0.1.34 |
| 0.1.32 | 0.1.32 - 0.1.34 |
| 0.1.30 | 0.1.30 - 0.1.34 |
| 0.1.29 | 0.1.29 - 0.1.34 |
| 0.1.28 | 0.1.28 - 0.1.34 |
| 0.1.27 | 0.1.27 - 0.1.34 |
| 0.1.26 | 0.1.26 - 0.1.34 |
| 0.1.25 | 0.1.25 - 0.1.34 |
| 0.1.24 | 0.1.24 - 0.1.34 |
| 0.1.23 | 0.1.23 - 0.1.34 |
| 0.1.22 | 0.1.22 - 0.1.34 |
| 0.1.21 | 0.1.21 - 0.1.34 |
| 0.1.20 | 0.1.20 - 0.1.34 |
| 0.1.19 | 0.1.19 - 0.1.34 |
| 0.1.18 | 0.1.18 - 0.1.34 |
| 0.1.17 | 0.1.17 - 0.1.34 |
| 0.1.16 | 0.1.16 - 0.1.34 |
| 0.1.15 | 0.1.15 - 0.1.34 |
| 0.1.14 | 0.1.14 - 0.1.34 |

**Comment by pascalberger** [comment]
> Exception to the rule: Add-ins targeting pre-release versions of Cake are pinned to the specific pre-release version they target.

That's a good point. We need to bump addin compatibility for 1.0 release. My idea was to do this during pre-release cycle, so that addin authors have enough time to get their addins ready for a 1.0 release when it ships. But this will then end in addins being built against e.g. 1.0.0-rc0002, which in theory should be compatible with 1.x. But I see also the point of saying pre-release is pre-release.
