### ISSUE TITLE
Thank you page

### ISSUE THREAD

**Issue by gep13** [cake-build/website#338]
To include information about people who help Cake.

Similar to what we have here:

https://github.com/cake-build/cake#thanks

**Comment by daveaglick** [comment]
Any interest in also pulling the contributors from GitHub and automatically adding them to the page?

**Comment by gep13** [comment]
@daveaglick yip, that sounds good to me 👍 

Again, this issue I think would go into the pile of ones for doing as a pairing session if you are up for it at some point.

**Comment by pascalberger** [comment]
Related to https://github.com/cake-build/website/issues/46
