### ISSUE TITLE
Link Update - Visual Studio Extension

### ISSUE THREAD

**Issue by fwinkelbauer** [cake-build/website#350]
The link to the Visual Studio extension on [this page](http://cakebuild.net/docs/editors/visualstudio) points to a working, but outdated [link](https://visualstudiogallery.msdn.microsoft.com/). Instead something like [this](https://marketplace.visualstudio.com/items?itemName=vs-publisher-1392591.CakeforVisualStudio) should be used

**Comment by gep13** [comment]
@fwinkelbauer are you in a position to send a PR through for this?

**Comment by fwinkelbauer** [comment]
I'll draft something after work, sure
