### ISSUE TITLE
Docs: Identify extension methods from addins

### ISSUE THREAD

**Issue by ChrisMaddock** [cake-build/website#375]
I just got a bit confused trying to get `MSBuildSettings.Dump()` to work.

![image](https://user-images.githubusercontent.com/4837132/27832556-fe7a6548-60c6-11e7-85fb-147c64c328e6.png)

It wasn't until I clicked through to the [actual page](http://cakebuild.net/api/Cake.Incubator/LoggingExtensions/D2217BAF) that there was anything to tell me that I needed to include an addin to access this method. Could we mark this somehow on the initial page?

**Comment by daveaglick** [comment]
Any suggestions on what the UI would look like? Maybe a small "Extrnsion from Xyz Addin" underneath the "From LoggingExtensions" text?

**Comment by ChrisMaddock** [comment]
Sounds good. Maybe even something more explicit that user-action needs to be taken?

```
Gets basic string representation
From LoggingExtensions
Requires MyAddin Cake Extension
```

**Comment by daveaglick** [comment]
PR incoming
![2017-10-18_14h56_54](https://user-images.githubusercontent.com/1020407/31737133-90452e72-b414-11e7-827d-4755918ed82f.png)

**Comment by ChrisMaddock** [comment]
Brilliant - thanks @daveaglick!
