### ISSUE TITLE
How do I use a nuget package in Cake?

### ISSUE THREAD

**Issue by chazt3n** [cake-build/website#388]
I'm receiving this error when running my script:

> error CS0246: The type or namespace name 'RestSharp' could not be fou
nd (are you missing a using directive or an assembly reference?)

**build.cake**
```cs
var target = Argument("target", "Default");

Task("Default")
  .Does(() => {
  var client = new RestSharp.RestClient("www.test.com");
  Information("Hello World!");
});

RunTarget(target);
```

**packages.config**

```xml
<?xml version="1.0" encoding="utf-8"?>
<packages>
    <package id="Cake" version="0.21.1" />
    <package id="RestSharp" version="105.2.3" />
</packages>
```

**Comment by chazt3n** [comment]
SOLVED: using [the addin preprocessor.](https://stackoverflow.com/questions/45198258/how-to-use-nuget-packages-in-cake-build-tool/45198549#45198549)

It would be nice if this was more clearly explained in the docs, thank you for such a cool tool!

**Comment by devlead** [comment]
@chazt3n glad it got sorted, any feedback how we can improve the fundamentals of the site is appreciated.

**Comment by chazt3n** [comment]
@devlead hey you helped me! Thank you again :)
When I looked back at your documentation, it _is_ clear about the differences between tools and add-ins
What I don't understand is how the packages.config comes into play

**Comment by gep13** [comment]
@chazt3n i added a comment on your SO question.

There are three packages.config files you can use...

* tools/packages.config
* tools/Addins/packages.config
* tools/Modules/packages.config

Each one works with the specific thing, i.e. Tools, Addins and Modules.

In order to make use of these you will need the latest bootstrapper.
