### ISSUE TITLE
Support For Interpolated String Literal Expressions

### ISSUE THREAD

**Issue by chazt3n** [cake-build/website#389]
It would be awesome to have support for code like:
```csharp
Console.WriteLine($"Name = {name}, hours = {hours:hh}");
```

**Comment by gep13** [comment]
Issue moved to [cake-build/cake #1691](https://github.com/cake-build/cake/issues/1691) via [**ZenHub**](https://www.zenhub.com/)

**Comment by chazt3n** [comment]
@gep13 beat me to it, sorry for wasting your time

**Comment by gep13** [comment]
@chazt3n I think this issue is best put into the other repository.
