### ISSUE TITLE
Add SSL Certificate to site

### ISSUE THREAD

**Issue by devlead** [cake-build/website#40]

**Comment by gep13** [comment]
@patriksvensson needs to make the website open to everyone in the team

**Comment by lextm** [comment]
https://cakebuild.net/ triggers a certificate warning in web browsers, so please consider fixing it in time. Chrome will soon show HTTP site as not secure.

One quick way to achieve so is to use a service such as CloudFlare who offers free certificates even for free tier users. It can be easily registered and configured by whoever owns the domain name.

**Comment by gep13** [comment]
@lextm yes, we are working on this. Thanks!

**Comment by gep13** [comment]
This has now been deployed...

https://cakebuild.net/
