### ISSUE TITLE
Another level of documentation

### ISSUE THREAD

**Issue by gep13** [cake-build/website#41]
Right now we have this:

![image](https://cloud.githubusercontent.com/assets/1271146/11604096/55a1e110-9ae0-11e5-8fcf-3571fcb143c9.png)

But it would be good to have:
- Fundamentals
  - Tasks
    - Another level

**Comment by daveaglick** [comment]
This is now possible so the only question is what to put/move to the deeper levels. Not sure if you want to track that here or if this issue was only for baseline support.

**Comment by devlead** [comment]
Then we can close this 👍
