### ISSUE TITLE
Document DoesForEach & DeferOnError

### ISSUE THREAD

**Issue by devlead** [cake-build/website#416]
cake-build/cake#1767 introduced DeferOnError and DoesForEach 

Should be documented on the website.

Samples here:
https://github.com/cake-build/cake/blob/develop/tests/integration/Cake.Core/CakeAliases.cake

```cake
Task("Awesome")
    .Does(() => { throw new Exception(); })
    .DoesForEach(GetFiles("**/*.txt"), (file) => { // My cool file action })
    .DeferOnError();
```

**Comment by phillipsj** [comment]
@devlead I am going to take this one.
