### ISSUE TITLE
Document NuGet.config configuration 

### ISSUE THREAD

**Issue by devlead** [cake-build/website#470]
cake-build/cake#1932 introduced Cake configuration for the location of NuGet.config and was released in 0.24.0, this should be documented among the other default values.

**Comment by mgnslndh** [comment]
I think this has already been resolved by #590 or am I missing something?

**Comment by pascalberger** [comment]
@mgnslndh You're right. Thanks for catching that 👍 

Closing as duplicate of https://github.com/cake-build/website/issues/590
