### ISSUE TITLE
Add info for authors on addin page

### ISSUE THREAD

**Issue by devlead** [cake-build/website#48]
Think we should add an short paragraph on the [addin](http://cakebuild.net/addins) page  [here](https://github.com/cake-build/website/blob/develop/src/Cake.Web/Views/Addin/Index.cshtml#L44) on how they go about submitting their addin to the Cake website.

**Comment by patriksvensson** [comment]
:+1:

**Comment by daveaglick** [comment]
There is now this text on the addins page:

> If you're an addin author and want your addin listed here, follow the instructions here.

Guessing this can be closed, @devlead can you please confirm?

**Comment by devlead** [comment]
yes 👍
