### ISSUE TITLE
Cake page has two Nugets options in Addins List.

### ISSUE THREAD

**Issue by devlead** [cake-build/website#489]
@nikhilagrawaldotnet commented on [Mon Feb 19 2018](https://github.com/cake-build/cake/issues/2043)

### What You Are Seeing?<br>
In http://cakebuild.net/addins/, there are two Nugets options in Addin's List namely 'Nuget' and 'NuGet'. Both takes us to same location - http://cakebuild.net/addins/nuget/.

![cake_issue](https://user-images.githubusercontent.com/26463468/36365604-467791c8-1570-11e8-8a30-37478021eb6f.jpg)

### What is Expected?
Single option. Two options confuse users.

### What version of Cake are you using?
N/A

### Are you running on a 32 or 64 bit system?
N/A

### What environment are you running on?  Windows? Linux? Mac?
N/A

### Are you running on a CI Server?  If so, which one?
N/A

### How Did You Get This To Happen? (Steps to Reproduce)
N/A

### Output Log
N/A

GIST LINK - Please create a gist and link to that gist here
N/A

OR

PLACE LOG CONTENT HERE
N/A

---

@gep13 commented on [Mon Feb 19 2018](https://github.com/cake-build/cake/issues/2043#issuecomment-366617629)

@daveaglick is there anything that we can do here?   Obviously, other than go to the addin's and ensure that there is consistency.

---

@devlead commented on [Mon Feb 19 2018](https://github.com/cake-build/cake/issues/2043#issuecomment-366618221)

Feels like potential ordinal ignore case fix, which is fine in this case but in other cases like C# thingies are case sensitive. But Categories most likely shouldn't be.

**Comment by daveaglick** [comment]
This certainly looks like a case comparison situation. The problem with making it insensitive is that it’ll be undefined which versions goes in first and wins. You may end up with all the NuGet addins going under “Nuget” or “nuget” when one of them uses the wrong case. Some hosts like GitHub Pages also use case sensitive URLs (which is crazy IMO) so the URL could change and break for all addins under that category if a new one is introduced with the wrong case.

Those are a lot of “what if’s” though - without looking at the code, I don’t think it would be hard to make the category grouping case insensitive and see how it goes.

**Comment by pascalberger** [comment]
This has been fixed by lowercasing all addin categories
