### ISSUE TITLE
API generics are unusable

### ISSUE THREAD

**Issue by jnm2** [cake-build/website#495]
Just the examples visible at the top of https://cakebuild.net/api/Cake.Common.Tools.NUnit/NUnit3Settings/:

![](https://user-images.githubusercontent.com/8040367/36733403-831766b0-1b9e-11e8-9baf-234c187cbe31.png)

- `Nullable<T>` should be rendered as `int?`
- `Func<T, TResult>` should be rendered as `Func<ProcessArgumentBuilder, ProcessArgumentBuilder>` and each `ProcessArgumentBuilder` should be a link.
- `IDictionary<TKey, TValue>` should be rendered as `IDictionary<string, string>`

**Comment by daveaglick** [comment]
The first item here regarding nullable display text should be resolved. Tracking generic type argument display in https://github.com/Wyamio/Wyam/issues/709. Tracking generic type argument linking in https://github.com/Wyamio/Wyam/issues/707.

**Comment by jnm2** [comment]
This is extremely cool! Just had to come back and say how helpful this has been! Thank you!

**Comment by daveaglick** [comment]
@jnm2 Thanks! Always nice to get positive feedback :smile:
