### ISSUE TITLE
Add a page describing how to pass information using arguments and env

### ISSUE THREAD

**Issue by nikhilagrawaldotnet** [cake-build/website#498]
Continuing from https://github.com/cake-build/website/pull/182, could we add a page describing how to pass multiple arguments to bootstrapper that can be passed to cake script.

Cheers :)

**Comment by gep13** [comment]
@nikhilagrawaldotnet are you in a position to do a PR for this?

**Comment by nikhilagrawaldotnet** [comment]
Will try.

**Comment by pascalberger** [comment]
This seems like a duplicate of #383
