### ISSUE TITLE
Problem with Aliases in the Reference Page

### ISSUE THREAD

**Issue by gep13** [cake-build/website#51]
I think we have a problem here:

![image](https://cloud.githubusercontent.com/assets/1271146/12053144/0a521454-af0e-11e5-82de-fd667c5058cf.png)

We have two built in Aliases for ReSharper:
- DupFinder
- InspectCode

and one external Alias from the Cake.ReSharperReports Addin.

The text which is being displayed in the screenshot above, i.e. "Contains aliases related to ReSharperReports API" is coming from the external Addin, same on this page:

![image](https://cloud.githubusercontent.com/assets/1271146/12053173/632f010e-af0e-11e5-9484-00bdc8149566.png)

Not sure how best to handle this, but I thought I would raise it so that we can start a discussion.

Thoughts? @patriksvensson @devlead

**Comment by daveaglick** [comment]
This looks to be resolved since the external aliases were moved to a "ReSharperReports" category. @gep13 can you confirm this one should be closed?

**Comment by gep13** [comment]
@daveaglick agreed, this can be closed.
