### ISSUE TITLE
Simpler documentation

### ISSUE THREAD

**Issue by polterguy** [cake-build/website#514]
First, love your work guys, awesome tool!

Secondly, as I started using Cake, I got stuck, not knowing how to actually get started. Hence, I have a suggestion. Create as your most wanted response (MWR) somewhere on your website a simple tutorial about how to get started. I spent about 30 minutes finding [this thing](http://cakebuild.net/docs/tutorials/setting-up-a-new-project). And I even had to post a support request, before I figured it out ...

Preferably, the above thing should (almost) be at the dead center of your landing page, since I assume the goal of the project is to get people to use the tool as fast as possible. Then create a small example Cake script, and have that below the above recipe, for doing _basic_ things such as creating a folder, copy a couple of files, and create a zip file from the result. Here's an example from my own actual usage ...

```csharp
/*
 * Creating root source code distribution folder, that
 * will later be zipped, after copying of all files is done.
 */
CreateDirectory("./phosphorusfive-8-1");

/*
 * Copying all source code file.
 *
 * We copy Hyperlambda files, C# files, and all (relevant) ASP.NET files.
 */
var files = GetFiles ("./**/*.cs$|*.hl$|*.md$|*.aspx$|*.ascx$|*.sh$|*.cake$|*.sln$|*.csproj$|*.asax$|*.ico$||*.css$|*.js$|*.png$|*.jpg$|*.jpeg$|*.gif$|*.svg$|LICENSE$|*.nupkg$|*.config$|*.targets$|*.txt$");
CopyFiles (files, "phosphorusfive-8-1", true);
files = GetFiles ("./packages/**/*");
CopyFiles (files, "phosphorusfive-8-1/packages/", true);

/*
 * Deleting "auth.hl" file.
 */
DeleteFile ("./phosphorusfive-8-1/core/p5.webapp/auth.hl");

... etc ...
```

And create __TINY__ YouTube videos, maximum 3-4 minutes long, that you embed into your site as an FAQ thing. [Here's an example of my own work](https://www.youtube.com/watch?v=C97Tkg6DgOY) ...

Notice, I was encouraged by some of the devs over [here](https://github.com/cake-build/cake/issues/2150#issuecomment-387850508) to post this. I think your tool is amazing, and really simple to use myself. However, as developers are looking to create a release, they're typically at the __END__ of a project cycle, and are probably putting in 100+ hours a week, to meet their own deadlines. And spending 50 minutes watching some YouTube video, going deeply into the system at such a time, you might as well ask people to give you their liver ...!! ;)

Thx for gr8 work :)

**Comment by gep13** [comment]
Thank you for the great feedback.  I definitely think that we can implement some of these suggestions.

We actually have an open PR for starting a FAQ section on the site:

https://github.com/cake-build/website/pull/445

There is an issue with it at the minute, which is stopping it from being implemented, but I think that is where we would end up putting some stuff.

I do have some short video tutorials for certain aspects of Cake, they are in my playlist here:

https://www.youtube.com/playlist?list=PL84yg23i9GBjQbwILV-jAV7B74csVskQd

Which would ultimately go into the FAQ section as well.  I have it on my todo list to create more videos, it is just a case of getting time.

**Comment by polterguy** [comment]
Awesome, I haven't started seeing these videos, but I presume they're good. Thought I'd like tore-iterate - 1-4 minutes max ... ;)

There's an attention span rule when it comes to developers, and goldfish, which is you've got 4 seconds to attract their attention, 4 minutes to prove you're worthy of keeping it, and 4 hours making them believe they can split the atom.

The header of your video==> 4 seconds ...

Its content ==> 4 minutes ...

Cake.exe ==> 4 hours ... ;)

**Comment by pascalberger** [comment]
The Getting Started documentation has been updated. [Setting Up A New Project](https://cakebuild.net/docs/getting-started/setting-up-a-new-project) is now linked from the landing page.
