### ISSUE TITLE
Review the Repository property in addins YAML file

### ISSUE THREAD

**Issue by Jericho** [cake-build/website#515]
The `Repository` property in addins yml file is used by the audit tool to determine if a given addin has been transferred to the cake-contrib or not. Therefore it's important the ensure this URL is correct.

I estimate that about 50 yml files have an incorrect url and therefore are deemed as "not transfered to cake-contrib" when in fact the ownership of the project has indeed been transferred.

**Comment by gep13** [comment]
@Jericho I have been through and updated the ones that were incorrect.

**Comment by Jericho** [comment]
Wow that was fast!

**Comment by gep13** [comment]
It was annoying me, so I had to fix it 😄
