### ISSUE TITLE
Formatting issues with examples in XmlPoke documentation

### ISSUE THREAD

**Issue by glennawatson** [cake-build/website#520]
### What You Are Seeing?
On the following pages I am seeing the last example (how to remove nodes) to not be formatted like the rest.  It is all collapsed into one sentence and doesn't have the clean formatting. 

http://cakebuild.net/api/Cake.Common.Xml/XmlPokeAliases/4B32572F http://cakebuild.net/api/Cake.Common.Xml/XmlPokeAliases/A9DB73CD
http://cakebuild.net/api/Cake.Common.Xml/XmlPokeAliases/8D143E37
http://cakebuild.net/api/Cake.Common.Xml/XmlPokeAliases/F742B364
### What is Expected?
That the web page examples all be consistently formatted.
### Are you running on a 32 or 64 bit system?
64 bit version
### What environment are you running on?  Windows? Linux? Mac?
Windows Chrome Version 66.0.3359.181 (Official Build) (64-bit)

### How Did You Get This To Happen? (Steps to Reproduce)
Go to one of the web sites listed above.

**Comment by daveaglick** [comment]
Thanks for reporting this. Looks like the XML comment tags are malformed. I.e., there should be a closing `</example>` tag here: https://github.com/cake-build/cake/blob/dc792050389cc3a8e460b1dd8ae83d61f09ff012/src/Cake.Common/Xml/XmlPokeAliases.cs#L83 and there's an extra closing tag further down.

I'll submit a PR to Cake.
