### ISSUE TITLE
Document compiler define pre processors directive 

### ISSUE THREAD

**Issue by devlead** [cake-build/website#558]
https://cakebuild.net/docs/fundamentals/preprocessor-directives

Example for reference 

https://github.com/cake-build/cake/blob/develop/tests/integration/Cake.Core/Scripting/DefineDirective.cake

**Comment by tomaszbartoszewski** [comment]
Hi, I added documentation, hopefully it's good enough. It's my first ever open source PR, so please let me know, if I did something wrong. I participate in hacktoberfest, and I think I need a label on my PR, but I can't add any labels. Are you adding labels to PRs?

Thank you very much
Tomasz

**Comment by devlead** [comment]
Fixed by #583

**Comment by pascalberger** [comment]
@tomaszbartoszewski Hacktoberfest doesn't require any specific labels on PRs to have them count towards your total. The `hacktoberfest` label is solely for promoting certain issues. See [FAQ](https://hacktoberfest.digitalocean.com/faq):

> Do issues have to be tagged #Hacktoberfest to count?
>
> No, any pull request made on a public repository counts, whether it's attached to a #Hacktoberfest issue or not.

**Comment by tomaszbartoszewski** [comment]
@pascalberger Hi, thank you for your answer, I checked my profile and I can see it there. Thanks for labeling issues, it is easier to start with it.
