### ISSUE TITLE
Show target .NET framework for an addin

### ISSUE THREAD

**Issue by patriksvensson** [cake-build/website#580]
Would be nice if we could show some addin requirements on the addin pages.

* .NET/Mono only?
* Windows only? (Not sure if this is doable)

Not sure what is needed for this to work, but just showing whether or not an addin is .NET/Mono only would be good. Might act as an incentive for people to multitarget as well.

Assigning @daveaglick since he explicitly asked for it 😄

**Comment by pascalberger** [comment]
Would also be nice to see against which version of Cake the addin was built (and it therefore requires)

**Comment by pascalberger** [comment]
> Would also be nice to see against which version of Cake the addin was built (and it therefore requires)

This is https://github.com/cake-build/website/issues/299

**Comment by augustoproiete** [comment]
I'm thinking about how one would implement this one.

> ### Show required .NET version
> - .NET/Mono only?

Would it make sense to display a list with all the .NET Target Frameworks of the add-in, on the right sidebar? Something along those lines:

![image](https://user-images.githubusercontent.com/177608/100534360-44b5c600-31e4-11eb-8b0e-fe2f797852b7.png)

I think TFM would be a good fit as it's shorter and devs should be familiar with it by now, but we could also display a more friendly name with target framework + version (e.g. .NET Standard 2.1).

---

> ### Windows only?

I don't think there's a way for us to determine *with certainty* if an add-in runs on Windows and/or Linux and/or OSX. I suggest we leave that for the add-in author to tell us by introducing a new attribute (or set of attributes) in `Cake.Core.Annotations` that the add-in author can apply at the assembly level to provide more information about the operating system the Cake add-in supports.

e.g.

```
[assembly: CakeSupportedOS("Linux")]
[assembly: CakeSupportedOS("MacOSX")]
[assembly: CakeSupportedOS("Windows")]
```

Is the above enough? Would it make more sense to be more specific with OS minimum version e.g. `Windows7`?

_It might make sense to move the this last part to a separate issue and tackle the Target Frameworks independently first_.

**Comment by pascalberger** [comment]
Original issue is already a few years old and some things have changed since then. I would suggest the following:

1. Show TFM on extension detail page (like you suggested)
2. Show compatible runners on extension detail page (this is probably what most users are interested in)
3. Add a filter on the extension overview page to filter to extensions which are available for specific runners

**Comment by augustoproiete** [comment]
Following up on this one:

> 1. Show TFM on extension detail page (like you suggested)

I'd suggest updating the AddinDiscoverer to enumerate the TFMs as part of the addin analysis it already does, and add this additional metadata to the YAML, and then the website can display it. /cc @Jericho

> 2. ~Show compatible runners on extension detail page (this is probably what most users are interested in)~

This was completed with #1288

> 3. Add a filter on the extension overview page to filter to extensions which are available for specific runners

I'll take a look at this one. It seems like a drop-down list with version ranges to choose from, unless you have a better idea

**Comment by pascalberger** [comment]
> > 1. ~Show compatible runners on extension detail page (this is probably what most users are interested in)~
> 
> This was completed with #1288

No, #1288 shows the Cake versions which have a compatible API. The idea here is to show which runners (not versions) the addin is compatible with (based on https://cakebuild.net/docs/running-builds/runners/#supported-platforms). E.g. if an addin targets net461 then it will work with Cake runner for .NET Framework, but not with Cake .NET Tool.

> > 1. Add a filter on the extension overview page to filter to extensions which are available for specific runners
> 
> I'll take a look at this one. It seems like a drop-down list with version ranges to choose from, unless you have a better idea

Also here it is mainly about runners: Coming from a user perspective I use a specific runner in a specific version running on a specific Framework version. It would be nice if I can enter information like this:

- Runner: Cake Runner for .NET Framework
- Runner Version: 0.37.0
- Runtime: .NET Framework 4.7.2

Every of the above criterias could work alone or in any combination

**Comment by Jericho** [comment]
> I'd suggest updating the AddinDiscoverer to enumerate the TFMs as part of the addin analysis it already does

I'd suggest reviewing the reports generated by the discoverer. You'll see that we already enumerate the TFMs. :wink:

> and add this additional metadata to the YAML

Sure, this can be added.

**Comment by pascalberger** [comment]
TFM are now available in the YAML files in the `TargetFrameworks` attribute

**Comment by pascalberger** [comment]
To make scope of this issue clear: Target Framework for extensions should be shown on the addin detail page.

Showing compatible runners or filtering is out of scope of this and can be done in a seprate PR.
