### ISSUE TITLE
Document nuget_configfile setting

### ISSUE THREAD

**Issue by mholo65** [cake-build/website#590]
Document [NuGet_ConfigFile setting](https://github.com/cake-build/cake/blob/e991ba8ed78ab920f8278ab036ef8d8d2360ea9f/src/Cake.NuGet/Constants.cs#L29)

https://gitter.im/cake-build/cake?at=5bdc617ab9c91919548e5d8f

**Comment by udemezue01** [comment]
how do i contribute

**Comment by devlead** [comment]
Fork repo, create feature branch from master, make changes submit PR.

This is the markdown file containing configuration values that need the addition:
https://github.com/cake-build/website/blob/master/input/docs/fundamentals/default-configuration-values.md
