### ISSUE TITLE
Display the documented version of an addin

### ISSUE THREAD

**Issue by daveaglick** [cake-build/website#686]
Since the site only shows API documents for the most recent version of an addin, it might be helpful to display that version somewhere for reference.

**Comment by mgnslndh** [comment]
@daveaglick I see that you are assigned to this issue. Is it something that you would like to do? If not I might want to take a stab at it.

**Comment by daveaglick** [comment]
Please feel free to pick it up @mgnslndh - most of my assignments are from a while ago before I started work on a new documentation engine. I'll eventually come back through and grab them again, but in the meantime it'd be awesome if anyone wanted to tackle some!
