### ISSUE TITLE
Official packages.json still refers to Cake 0.9.0

### ISSUE THREAD

**Issue by hal-ler** [cake-build/website#71]
Hate to be the guy to report all these small things, but http://cakebuild.net/bootstrapper/packages generates the following packages.config file:
`<?xml version="1.0" encoding="utf-8"?>`
`<packages>`
	`<package id="Cake" version="0.9.0" />`
`</packages>`

**Comment by devlead** [comment]
@hal-ler  thanks your feedback :+1: , we are aware of why this occurs and are working on releasing a hotfix for this, we just need some more testing of the the Cake release process.

**Comment by gep13** [comment]
@hal-ler this has now been resolved.  Thanks!
