### ISSUE TITLE
Overhaul and unify Cake bootstrapping and execution samples

### ISSUE THREAD

**Issue by devlead** [cake-build/website#878]
Current recommended approaches utilizing. NET framework or Mono should no longer be the default preferred way, still documented but not front and center. 

Best and preferred way should be executing using .NET Core CLI, tool manifest, etc. 
This will make cross platform execution story more consistent and acquiring process more clear. 

Reference cake-build/cake#1690

**Comment by patriksvensson** [comment]
Related: https://github.com/cake-build/cake/issues/2776

**Comment by pascalberger** [comment]
Documentation for [runners](https://cakebuild.net/docs/getting-started/running-cake-scripts) and [bootstrapping scripts](https://cakebuild.net/docs/getting-started/bootstrapping-scripts) have been updated with .NET Core Tool as the recommended approach.
