### ISSUE TITLE
Document environment variable for showing what a tool is executing (Settings_ShowProcessCommandLine)

### ISSUE THREAD

**Issue by gep13** [cake-build/website#907]
This was added in this PR:

https://github.com/cake-build/cake/pull/2486

And I think we need to capture this, somewhere, on the site.

**Comment by mgnslndh** [comment]
I can do this. Not sure where the info needs to be captured though. Perhaps on the page for [default configuration values](https://cakebuild.net/docs/fundamentals/default-configuration-values)? But this configuration is only available through an environment variable and not through the config file or command line I guess.

**Comment by pascalberger** [comment]
Best solution would be to restructure content a little bit first (current structure shows its age 😄). My idea would be to have a `Configuration` section under `Documentation` (same level as `Fundamentals`) where the existing config values can be moved to, but also additional and currently missing configuration options be added. Once this is done, this can be added as a second page documenting environment variables. 

If this is OK for you I would suggest to do it in two pull requests: The first changing structure of the existing documentation and the second adding the content for this issue.

**Comment by mgnslndh** [comment]
Sure, two PR is fine. 

# 1st PR

So we leave `fundamentals/configuration.md` as-is, explaining **how** configuration is done but we move the description of available configuration options to its own top level section. Or do you prefer having `fundamentals/configuration.md`  moved to something like `configuration/index.md`?

`fundamentals/default-configuration-values.md` is moved to `configuration/index.md` or `configuration/options.md` depending or you preference regarding my question above.

Missing configuration options needs to be identified and documented as well.

# 2nd PR

However, regarding the second PR splitting `fundamentals/default-configuration-values.md` into multiple pages i'm not sure. We would need to have three pages (file, env, cli) and each configuration option would need to have the same description and default value on each page. See mockups below.

### configuration/environment-variables.md
![image](https://user-images.githubusercontent.com/1139118/95045357-28b10f00-06e2-11eb-864c-a95bc428df6d.png)

### configuration/configuration-file.md
![image](https://user-images.githubusercontent.com/1139118/95045797-11beec80-06e3-11eb-9e14-4cef349cd3e6.png)

### configuration/command-line.md
![image](https://user-images.githubusercontent.com/1139118/95045938-5ea2c300-06e3-11eb-8797-b03eadd2b7fc.png)

**Comment by pascalberger** [comment]
Sorry for the later reply. Missed your answer.

> 1st PR

I would suggest to have `docs/configuration/` giving a brief introduction to configuration for Cake, plus the list of sub-pages (like e.g. done at https://cakebuild.net/docs/extending/modules/). This would be in the `index.cshtml` file. I think the most part of `docs/fundamentals/configuration.md` can be moved to something like `docs/configuration/set-configuration-values.md`. 

> fundamentals/default-configuration-values.md is moved to configuration/index.md or configuration/options.md depending or you preference regarding my question above.

I would suggest to move this to `configuration/options.md`.

> 2nd PR

You're correct, that it probably doesn't make much sense to have all this duplicate documentation. I would suggest to have a single page, where for each option the different values are shown (either through headings or in a table).

**Comment by pascalberger** [comment]
@mgnslndh I did some restructuration yesterday. Configuration documentation is now available at https://cakebuild.net/docs/running-builds/configuration and https://cakebuild.net/docs/running-builds/default-configuration-values. Still would suggest to merge them in single node with sub-pages.

**Comment by mgnslndh** [comment]
Seems much better to have configuration under "Running Builds". Nice move 👍 

I see that you have `RedirectFrom` frontmatter pointing to the old locations. Should I update these so that they points to the current locations? What will then happen when you navigate to the urls you redirect from?

**Comment by pascalberger** [comment]
> Seems much better to have configuration under "Running Builds". Nice move 👍
> 
> I see that you have `RedirectFrom` frontmatter pointing to the old locations. Should I update these so that they points to the current locations? What will then happen when you navigate to the urls you redirect from?

Yes, if we move stuff around we should add the `RedirectFrom` frontmatter, which will create an HTML file at the old location containing a redirect to the new location.

**Comment by pascalberger** [comment]
> Also, wouldn't it make sense to order "Writing Builds" before "Running Builds"?

I see different groups of stakeholders for Cake:

1. People working in repos containing a Cake build script
2. Developers writing build scripts
3. Developers writing extensions for Cake / Developers contributing to Cake

The idea behind having the chapter how to run builds before how to write scripts was, that running of build scripts is something all stakeholders affects. While writing scripts only affects 2. and 3. and extending cake only affects 3.

What was your idea for sorting Writing before Running?

**Comment by mgnslndh** [comment]
That makes total sense. I was only considering group number 2. But when I think about it it makes more sense to optimize for group 1.

**Comment by pascalberger** [comment]
@mgnslndh Are you still working on this?

**Comment by mgnslndh** [comment]
@pascalberger  I kind of forgot about this issue after all the restructuring. Added PR #1238 for the actual documentation. What do you think?

**Comment by pascalberger** [comment]
> @pascalberger I kind of forgot about this issue after all the restructuring. Added PR #1238 for the actual documentation. What do you think?

@mgnslndh Thank you very much 👍  LGTM and will merge once the build is successful
