### ISSUE TITLE
Integrate / merge reference and addin sites

### ISSUE THREAD

**Issue by pascalberger** [cake-build/website#927]
Currently the addin site shows me a list of addins, but I can't navigate from there to the documentation of the aliases provided by the addin. We should integrate the functionality of the reference and the addin sites in a single page.

**Comment by gep13** [comment]
I think this makes a lot of sense!

**Comment by pascalberger** [comment]
Mockup for a new extension page which can replace the current addin page and which will show aliases for a specific addin: https://github.com/cake-build/website/issues/1096#issuecomment-711096108
