### ISSUE TITLE
Add community / help section

### ISSUE THREAD

**Issue by pascalberger** [cake-build/website#928]
We should add a section about how to get help for users, linking to GitHub discussions, etc

**Comment by karkranikhil** [comment]
Assign it to me i will try

**Comment by pascalberger** [comment]
@karkranikhil Thanks for giving this a try 👍 

Currently we promote exclusively our [Gitter channel](https://gitter.im/cake-build/cake) on the website. We would like to move to [GitHub Discussion](https://github.com/cake-build/cake/discussions) going forward. Like the Gitter channel today, the idea of GitHub Discussion is to be a place for the community to connect with other community members about Cake.

For us it is important that we don't raise expectations that there is support on an enterprise level available, but it's a community effort. The new page should reflect this. Therefore I would suggest to introduce a new "Community" entry in the top level navigation, where in the future we can also bundle stuff like [Resources](https://cakebuild.net/docs/resources/), [Contribution info](https://cakebuild.net/docs/contributing/) (but this is out of scope of this issue).

Rough steps for this issues are:

* Remove the Open Chat window on the website
* Introduce a new community top level navigation entry
* Add a dedicated "Help" page to the community entry mentioning Discussions and Issues
* Mention Gitter as an archive on the "Help" page

**Comment by pascalberger** [comment]
@karkranikhil Are you still interested in giving this a try? If you need any further information?

**Comment by karkranikhil** [comment]
Sorry for the late reply. Can you give me the design?

**Comment by pascalberger** [comment]
@karkranikhil What exactly do you mean with design? This shouldn't require any additional graphical design in the first step, just a new markdown page styled in the default styling of the website (see steps [here](https://github.com/cake-build/website/issues/928#issuecomment-702558183)).
