### ISSUE TITLE
Add documentation for sharing of code

### ISSUE THREAD

**Issue by pascalberger** [cake-build/website#932]
We should have documentation which shows the different possibilities to share code across multiple repos (Recipe scripts, addins, modules, ..)

**Comment by gep13** [comment]
@pascalberger this would be a great addition!

**Comment by pascalberger** [comment]
See also #25 and https://github.com/cake-build/cake/issues/488 for similar requests

**Comment by pascalberger** [comment]
See also https://github.com/cake-build/website/issues/26
