### ISSUE TITLE
Clear Cloudflare cache on deployment

### ISSUE THREAD

**Issue by pascalberger** [cake-build/website#933]
We should clear Cloudflare cache after deploying a new version of the site.

**Comment by gep13** [comment]
@pascalberger this is how I have done it in the past:

https://github.com/cake-contrib/Cake.Wyam.Recipe/blob/develop/Cake.Wyam.Recipe/Content/wyam.cake#L80-L99

That clears EVERYTHING though.

**Comment by gep13** [comment]
@pascalberger is this something that we still want to add?

**Comment by pascalberger** [comment]
Definitely. I had several times issues when changing CSS files, that I needed to manually delete Cloudflare cache, to make it work. We could get around it by implementing proper cache busting (e.g. by adding timestamp to filenames), but it is probably less effort to just delete cache.

**Comment by gep13** [comment]
Ok, cool, I will take on this issue as well then.
