### ISSUE TITLE
Document available preprocessor defines

### ISSUE THREAD

**Issue by pascalberger** [cake-build/website#963]
We should document available preprocessor defines (defined [here](https://github.com/cake-build/cake/blob/142cd24779129925e4e09a2d17a6a481782f31dc/src/Cake.Core/Scripting/ScriptConventions.cs#L121-L123)) on https://cakebuild.net/docs/fundamentals/preprocessor-directives

**Comment by mgnslndh** [comment]
I can do this one. Seems like it is a good issue to begin with.

**Comment by pascalberger** [comment]
@mgnslndh Great! Let me know if you have any questions or need more information.
